### PR TITLE
Fix import of FriendDecl

### LINKED ISSUE #262: Assert in clang::Decl::setObjectOfFriendDecl
```
llvm/tools/clang/include/clang/AST/DeclBase.h:1040: void clang::Decl::setObjectOfFriendDecl(bool): Assertion `!(OldNS & ~(IDNS_Tag | IDNS_Ordinary | IDNS_Type | IDNS_TagFriend | IDNS_OrdinaryFriend | IDNS_LocalExtern)) && "namespace includes other than ordinary or tag"' failed.
```

### PR DESCRIPTION
**Pull request by martong**
Fixes #262 

The crux of the problem was that during import we did not set up the `IdentifierNamespace` of the `Decl`s. This caused that the imported `ToFriendD` had wrong IDNS value, which in turn caused the assertion in `setObjectOfFriendDecl()`.

### CODE REVIEW

File: lib/AST/ASTImporter.cpp [hunk 1]
```diff
@@ -2747,11 +2747,8 @@ Decl *ASTNodeImporter::VisitFriendDecl(FriendDecl *D) {
   FriendDecl::FriendUnion ToFU;
   if (NamedDecl *FriendD = D->getFriendDecl()) {
     auto ToFriendD = cast_or_null<NamedDecl>(Importer.Import(FriendD));
-    if (ToFriendD && FriendD->getFriendObjectKind())
```
Comment (Xazax-hun) [inline lib/AST/ASTImporter.cpp]: Why did we need this change?

File: unittests/AST/ASTImporterTest.cpp [hunk 2]
```diff
@@ -1066,5 +1087,49 @@ TEST_F(Fixture,
...
+
+  MatchVerifier<Decl> Verifier;
+  auto Matcher = functionDecl();
+  ASSERT_TRUE(Verifier.match(From, Matcher));
+  EXPECT_TRUE(Verifier.match(To, Matcher));
+  EXPECT_EQ(From->getIdentifierNamespace(), To->getIdentifierNamespace());
+}
+
+// Matcher class to retrieve the last matched node under a given AST.
+template <typename NodeType> class Matcher : public MatchFinder::MatchCallback {
```
Comment (gerazo) [inline unittests/AST/ASTImporterTest.cpp]: I would name this according to its role... like LastMatcher instead of a too general name.

File: lib/AST/ASTImporter.cpp [hunk 3]
```diff
@@ -2747,11 +2747,8 @@ Decl *ASTNodeImporter::VisitFriendDecl(FriendDecl *D) {
...
-      ToFriendD->setObjectOfFriendDecl();
```
Comment (gerazo) [inline lib/AST/ASTImporter.cpp]: So you no longer need this to be called on the target? Can IdentifierNamespace equality substitute for this?

Comment (martong) [reply lib/AST/ASTImporter.cpp]: Exactly.
`setObjectOfFriendDecl` sets the member `IdentifierNamespace` to value which represent that the `Decl` is a friend.
But that is already handled with `ToD->IdentifierNamespace = FromD->IdentifierNamespace;` in `Import(Decl* FromD)`.
