### PR TITLE
Fix redecl chain of classes and class templates

### LINKED ISSUE #484: Assertion `isa<InjectedClassNameType>(Decl->TypeForDecl)` failed
During analysis of bitcoin we have this assertion.
```
#0  0x00007fffedf52428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fffedf5402a in __GI_abort () at abort.c:89
#2  0x00007fffedf4abd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7fffea89f69f "isa<InjectedClassNameType>(Decl->TypeForDecl)", file=file@entry=0x7fffea89d059 "../../git/llvm/tools/clang/lib/AST/ASTContext.cpp", line=line@entry=3664, function=function@entry=0x7fffea89f634 "clang::QualType clang::ASTContext::getInjectedClassNameType(clang::CXXRecordDecl *, clang::QualType) const") at assert.c:92
#3  0x00007fffedf4ac82 in __GI___assert_fail (assertion=0x7fffea89f69f "isa<InjectedClassNameType>(Decl->TypeForDecl)", file=0x7fffea89d059 "../../git/llvm/tools/clang/lib/AST/ASTContext.cpp", line=3664, function=0x7fffea89f634 "clang::QualType clang::ASTContext::getInjectedClassNameType(clang::CXXRecordDecl *, clang::QualType) const") at assert.c:101
#4  0x00007fffea34835a in clang::ASTContext::getInjectedClassNameType (this=0x6a4ac0, Decl=0xafd3198, TST=...) at ../../git/llvm/tools/clang/lib/AST/ASTContext.cpp:3664
#5  0x00007fffea4d5d7f in clang::ASTNodeImporter::VisitRecordDecl (this=0x7ffffffe50c0, D=0x90dd560) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2401
#6  0x00007fffea530b88 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::VisitCXXRecordDecl (this=0x7ffffffe50c0, D=0x90dd560) at tools/clang/include/clang/AST/DeclNodes.inc:251
#7  0x00007fffea50bca0 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe50c0, D=0x90dd560) at tools/clang/include/clang/AST/DeclNodes.inc:251
#8  0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x90dd560) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#9  0x00007fffea4e42c7 in clang::ASTNodeImporter::VisitClassTemplateDecl (this=0x7ffffffe5430, D=0x90dd148) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4523
(More stack frames follow...)
(gdb) bt
#0  0x00007fffedf52428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fffedf5402a in __GI_abort () at abort.c:89
#2  0x00007fffedf4abd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7fffea89f69f "isa<InjectedClassNameType>(Decl->TypeForDecl)", file=file@entry=0x7fffea89d059 "../../git/llvm/tools/clang/lib/AST/ASTContext.cpp", line=line@entry=3664, function=function@entry=0x7fffea89f634 "clang::QualType clang::ASTContext::getInjectedClassNameType(clang::CXXRecordDecl *, clang::QualType) const") at assert.c:92
#3  0x00007fffedf4ac82 in __GI___assert_fail (assertion=0x7fffea89f69f "isa<InjectedClassNameType>(Decl->TypeForDecl)", file=0x7fffea89d059 "../../git/llvm/tools/clang/lib/AST/ASTContext.cpp", line=3664, function=0x7fffea89f634 "clang::QualType clang::ASTContext::getInjectedClassNameType(clang::CXXRecordDecl *, clang::QualType) const") at assert.c:101
#4  0x00007fffea34835a in clang::ASTContext::getInjectedClassNameType (this=0x6a4ac0, Decl=0xafd3198, TST=...) at ../../git/llvm/tools/clang/lib/AST/ASTContext.cpp:3664
#5  0x00007fffea4d5d7f in clang::ASTNodeImporter::VisitRecordDecl (this=0x7ffffffe50c0, D=0x90dd560) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2401
#6  0x00007fffea530b88 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::VisitCXXRecordDecl (this=0x7ffffffe50c0, D=0x90dd560) at tools/clang/include/clang/AST/DeclNodes.inc:251
#7  0x00007fffea50bca0 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe50c0, D=0x90dd560) at tools/clang/include/clang/AST/DeclNodes.inc:251
#8  0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x90dd560) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#9  0x00007fffea4e42c7 in clang::ASTNodeImporter::VisitClassTemplateDecl (this=0x7ffffffe5430, D=0x90dd148) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4523
#10 0x00007fffea50bbdc in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe5430, D=0x90dd148) at tools/clang/include/clang/AST/DeclNodes.inc:195
#11 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x90dd148) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#12 0x00007fffea4e3bfc in clang::ASTNodeImporter::VisitClassTemplateDecl (this=0x7ffffffe57a0, D=0x90f0610) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4454
#13 0x00007fffea50bbdc in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe57a0, D=0x90f0610) at tools/clang/include/clang/AST/DeclNodes.inc:195
#14 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x90f0610) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#15 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffe5d00, FromDC=0x8cceaf8, ForceImport=false, ToDC=0x0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#16 0x00007fffea4d208d in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffe5d00, D=0x8ccead0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1879
#17 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe5d00, D=0x8ccead0) at tools/clang/include/clang/AST/DeclNodes.inc:105
#18 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8ccead0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#19 0x00007fffea4cd21e in clang::ASTImporter::ImportContext (this=0xa69af60, FromDC=0x8cceaf8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7234
#20 0x00007fffea4ccf25 in clang::ASTNodeImporter::ImportDeclParts (this=0x7ffffffe6140, D=0x9c93538, DC=@0x7ffffffe6028: 0x7ffffffe60b8, LexicalDC=@0x7ffffffe6020: 0x7ffffffe6060, Name=..., ToD=@0x7ffffffe6008: 0xaf08fa0, Loc=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1149
#21 0x00007fffea4e68ff in clang::ASTNodeImporter::VisitFunctionTemplateDecl (this=0x7ffffffe6140, D=0x9c93538) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4978
#22 0x00007fffea50bbf8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe6140, D=0x9c93538) at tools/clang/include/clang/AST/DeclNodes.inc:201
#23 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x9c93538) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#24 0x00007fffea4f33a2 in clang::ASTNodeImporter::VisitUnresolvedLookupExpr (this=0x7ffffffe6670, E=0xb011fb0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6775
#25 0x00007fffea50d94b in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7ffffffe6670, S=0xb011fb0) at tools/clang/include/clang/AST/StmtNodes.inc:721
#26 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xb011fb0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#27 0x00007fffea4c9eb5 in clang::ASTImporter::Import (this=0xa69af60, FromE=0xb011fb0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7289
#28 0x00007fffea4f389e in clang::ASTNodeImporter::VisitCallExpr (this=0x7ffffffe6a60, E=0xb013b38) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6807
#29 0x00007fffea532388 in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::VisitCXXOperatorCallExpr (this=0x7ffffffe6a60, S=0xb013b38) at tools/clang/include/clang/AST/StmtNodes.inc:345
#30 0x00007fffea50d32b in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7ffffffe6a60, S=0xb013b38) at tools/clang/include/clang/AST/StmtNodes.inc:345
#31 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xb013b38) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#32 0x00007fffea4c9eb5 in clang::ASTImporter::Import (this=0xa69af60, FromE=0xb013b38) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7289
#33 0x00007fffea4cf636 in clang::ASTNodeImporter::ImportDefinition (this=0x7ffffffe7070, From=0xb011d80, To=0xafd3138, Kind=clang::ASTNodeImporter::IDK_Default) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1427
#34 0x00007fffea4dc765 in clang::ASTNodeImporter::VisitVarDecl (this=0x7ffffffe7070, D=0xb011d80) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:3299
#35 0x00007fffea50bf5c in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe7070, D=0xb011d80) at tools/clang/include/clang/AST/DeclNodes.inc:441
#36 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xb011d80) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#37 0x00007fffea4f6450 in clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_1::operator()(clang::Decl*) const (this=0x7ffffffe70e8, D=0xb011d80) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5043
#38 0x00007fffea4e7006 in std::transform<clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_1>(clang::Decl**, clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_1) (__first=0x7ffffffe7180, __last=0x7ffffffe7188, __result=0x7ffffffe7160, __unary_op=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306
#39 0x00007fffea4e6f74 in clang::ASTNodeImporter::ImportDeclGroup (this=0x7ffffffe7350, DG=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5041
#40 0x00007fffea4e786b in clang::ASTNodeImporter::VisitDeclStmt (this=0x7ffffffe7350, S=0xb013d30) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5130
#41 0x00007fffea50cece in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7ffffffe7350, S=0xb013d30) at tools/clang/include/clang/AST/StmtNodes.inc:103
#42 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xb013d30) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#43 0x00007fffea52aee7 in bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const (this=0x7ffffffe7430, From=0xb013d30) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:472
#44 0x00007fffea52ae8a in std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) (__first=0xb013ed8, __last=0xb013ef8, __result=0x7ffffffe75b0, __unary_op=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306
#45 0x00007fffea52adf0 in clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**> (this=0x7ffffffe76f0, Ibegin=0xb013ec0, Iend=0xb013ef8, Obegin=0x7ffffffe7598) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:469
Python Exception <class 'gdb.error'> There is no member or method named Size.:
#46 0x00007fffea501d1c in clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> > (this=0x7ffffffe76f0, InContainer=..., OutContainer=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:483
#47 0x00007fffea4e7abc in clang::ASTNodeImporter::VisitCompoundStmt (this=0x7ffffffe76f0, S=0xb013eb0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5149
#48 0x00007fffea50ce5e in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7ffffffe76f0, S=0xb013eb0) at tools/clang/include/clang/AST/StmtNodes.inc:79
#49 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xb013eb0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#50 0x00007fffea4d8e08 in clang::ASTNodeImporter::VisitFunctionDecl (this=0x7ffffffe80a0, D=0xb00e3f0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2836
#51 0x00007fffea4d983d in clang::ASTNodeImporter::VisitCXXMethodDecl (this=0x7ffffffe80a0, D=0xb00e3f0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2878
#52 0x00007fffea50beb4 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe80a0, D=0xb00e3f0) at tools/clang/include/clang/AST/DeclNodes.inc:399
#53 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xb00e3f0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#54 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffe8558, FromDC=0xb00d000, ForceImport=true, ToDC=0xafcfc58) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#55 0x00007fffea4ceabe in clang::ASTNodeImporter::ImportDefinition (this=0x7ffffffe8558, From=0xb00cfc8, To=0xafcfc20, Kind=clang::ASTNodeImporter::IDK_Default) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1413
#56 0x00007fffea4cdc82 in clang::ASTNodeImporter::ImportDefinitionIfNeeded (this=0x7ffffffe8558, FromD=0xb00cfc8, ToD=0xafcfc20) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1184
#57 0x00007fffea4cdb7c in clang::ASTImporter::GetAlreadyImportedOrNull (this=0xa69af60, FromD=0xb00cfc8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7174
#58 0x00007fffea4c8607 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xb00cfc8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7212
#59 0x00007fffea4e42c7 in clang::ASTNodeImporter::VisitClassTemplateDecl (this=0x7ffffffe8980, D=0xb00ce78) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4523
#60 0x00007fffea50bbdc in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe8980, D=0xb00ce78) at tools/clang/include/clang/AST/DeclNodes.inc:195
#61 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xb00ce78) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#62 0x00007fffea4d5b92 in clang::ASTNodeImporter::VisitRecordDecl (this=0x7ffffffe8ff0, D=0xb00cfc8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2381
#63 0x00007fffea530b88 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::VisitCXXRecordDecl (this=0x7ffffffe8ff0, D=0xb00cfc8) at tools/clang/include/clang/AST/DeclNodes.inc:251
#64 0x00007fffea50bca0 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe8ff0, D=0xb00cfc8) at tools/clang/include/clang/AST/DeclNodes.inc:251
#65 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xb00cfc8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#66 0x00007fffea4e42c7 in clang::ASTNodeImporter::VisitClassTemplateDecl (this=0x7ffffffe9360, D=0xb00ce78) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4523
#67 0x00007fffea50bbdc in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe9360, D=0xb00ce78) at tools/clang/include/clang/AST/DeclNodes.inc:195
#68 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xb00ce78) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#69 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffe98c0, FromDC=0xae717b0, ForceImport=false, ToDC=0x0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#70 0x00007fffea4d208d in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffe98c0, D=0xae71788) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1879
#71 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe98c0, D=0xae71788) at tools/clang/include/clang/AST/DeclNodes.inc:105
#72 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae71788) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#73 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffe9e20, FromDC=0xae6be80, ForceImport=false, ToDC=0x0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#74 0x00007fffea4d208d in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffe9e20, D=0xae6be58) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1879
#75 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffe9e20, D=0xae6be58) at tools/clang/include/clang/AST/DeclNodes.inc:105
#76 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae6be58) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#77 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffea380, FromDC=0x8d93bf0, ForceImport=false, ToDC=0x0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#78 0x00007fffea4d208d in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffea380, D=0x8d93bc8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1879
#79 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffea380, D=0x8d93bc8) at tools/clang/include/clang/AST/DeclNodes.inc:105
#80 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8d93bc8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#81 0x00007fffea4cd21e in clang::ASTImporter::ImportContext (this=0xa69af60, FromDC=0x8d93bf0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7234
#82 0x00007fffea4ccf25 in clang::ASTNodeImporter::ImportDeclParts (this=0x7ffffffea8b0, D=0xae6be58, DC=@0x7ffffffea740: 0x7ffffffea760, LexicalDC=@0x7ffffffea738: 0xa69afb0, Name=..., ToD=@0x7ffffffea720: 0x7ffffffea790, Loc=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1149
#83 0x00007fffea4d1943 in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffea8b0, D=0xae6be58) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1819
#84 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffea8b0, D=0xae6be58) at tools/clang/include/clang/AST/DeclNodes.inc:105
#85 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae6be58) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#86 0x00007fffea4cd21e in clang::ASTImporter::ImportContext (this=0xa69af60, FromDC=0xae6be80) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7234
#87 0x00007fffea4ccf25 in clang::ASTNodeImporter::ImportDeclParts (this=0x7ffffffeade0, D=0xae71788, DC=@0x7ffffffeac70: 0x7ffffffeac90, LexicalDC=@0x7ffffffeac68: 0xa69afb0, Name=..., ToD=@0x7ffffffeac50: 0x7ffffffeacc0, Loc=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1149
#88 0x00007fffea4d1943 in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffeade0, D=0xae71788) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1819
#89 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffeade0, D=0xae71788) at tools/clang/include/clang/AST/DeclNodes.inc:105
#90 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae71788) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#91 0x00007fffea4cd21e in clang::ASTImporter::ImportContext (this=0xa69af60, FromDC=0xae717b0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7234
#92 0x00007fffea4ccf25 in clang::ASTNodeImporter::ImportDeclParts (this=0x7ffffffeb330, D=0xae78248, DC=@0x7ffffffeb1b8: 0xa69afb0, LexicalDC=@0x7ffffffeb1b0: 0xaf08fa0, Name=..., ToD=@0x7ffffffeb198: 0x7ffffffeb288, Loc=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1149
#93 0x00007fffea4e3cb3 in clang::ASTNodeImporter::VisitClassTemplateDecl (this=0x7ffffffeb330, D=0xae78248) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4466
#94 0x00007fffea50bbdc in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffeb330, D=0xae78248) at tools/clang/include/clang/AST/DeclNodes.inc:195
#95 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae78248) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#96 0x00007fffea4cb830 in clang::ASTImporter::Import (this=0xa69af60, From=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7453
#97 0x00007fffea4cb548 in clang::ASTNodeImporter::VisitTemplateSpecializationType (this=0x7ffffffeb6f0, T=0xb009000) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:984
#98 0x00007fffea50b318 in clang::TypeVisitor<clang::ASTNodeImporter, clang::QualType>::Visit (this=0x7ffffffeb6f0, T=0xb009000) at ../../git/llvm/tools/clang/include/clang/AST/TypeNodes.def:99
#99 0x00007fffea4c89a5 in clang::ASTImporter::Import (this=0xa69af60, FromT=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7145
#100 0x00007fffea4cbf29 in clang::ASTNodeImporter::VisitElaboratedType (this=0x7ffffffeb8a0, T=0xb009060) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1014
#101 0x00007fffea50b28c in clang::TypeVisitor<clang::ASTNodeImporter, clang::QualType>::Visit (this=0x7ffffffeb8a0, T=0xb009060) at ../../git/llvm/tools/clang/include/clang/AST/TypeNodes.def:94
#102 0x00007fffea4c89a5 in clang::ASTImporter::Import (this=0xa69af60, FromT=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7145
#103 0x00007fffea4d2b2e in clang::ASTNodeImporter::VisitTypedefNameDecl (this=0x7ffffffebd00, D=0xae781e8, IsAlias=false) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1978
#104 0x00007fffea4d30af in clang::ASTNodeImporter::VisitTypedefDecl (this=0x7ffffffebd00, D=0xae781e8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2009
#105 0x00007fffea50bd48 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffebd00, D=0xae781e8) at tools/clang/include/clang/AST/DeclNodes.inc:303
#106 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae781e8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#107 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffec770, FromDC=0xae75390, ForceImport=true, ToDC=0xafcf850) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#108 0x00007fffea4ceabe in clang::ASTNodeImporter::ImportDefinition (this=0x7ffffffec770, From=0xae75358, To=0xafcf818, Kind=clang::ASTNodeImporter::IDK_Default) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1413
#109 0x00007fffea4e53c3 in clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl (this=0x7ffffffec770, D=0xae75358) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4723
#110 0x00007fffea530bb8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::VisitClassTemplatePartialSpecializationDecl (this=0x7ffffffec770, D=0xae75358) at tools/clang/include/clang/AST/DeclNodes.inc:259
#111 0x00007fffea50bcd8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffec770, D=0xae75358) at tools/clang/include/clang/AST/DeclNodes.inc:259
#112 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae75358) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#113 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffeccd0, FromDC=0xae6c4f0, ForceImport=false, ToDC=0x0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#114 0x00007fffea4d208d in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffeccd0, D=0xae6c4c8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1879
#115 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffeccd0, D=0xae6c4c8) at tools/clang/include/clang/AST/DeclNodes.inc:105
#116 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae6c4c8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#117 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffed230, FromDC=0xae6aeb0, ForceImport=false, ToDC=0x0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#118 0x00007fffea4d208d in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffed230, D=0xae6ae88) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1879
#119 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffed230, D=0xae6ae88) at tools/clang/include/clang/AST/DeclNodes.inc:105
#120 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae6ae88) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#121 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffed790, FromDC=0x8d940b8, ForceImport=false, ToDC=0x0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#122 0x00007fffea4d208d in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffed790, D=0x8d94090) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1879
#123 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffed790, D=0x8d94090) at tools/clang/include/clang/AST/DeclNodes.inc:105
#124 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8d94090) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#125 0x00007fffea4cd21e in clang::ASTImporter::ImportContext (this=0xa69af60, FromDC=0x8d940b8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7234
#126 0x00007fffea4ccf25 in clang::ASTNodeImporter::ImportDeclParts (this=0x7ffffffedcc0, D=0xae6ae88, DC=@0x7ffffffedb50: 0x7ffffffedb70, LexicalDC=@0x7ffffffedb48: 0xa69afb0, Name=..., ToD=@0x7ffffffedb30: 0x7ffffffedba0, Loc=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1149
#127 0x00007fffea4d1943 in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffedcc0, D=0xae6ae88) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1819
#128 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffedcc0, D=0xae6ae88) at tools/clang/include/clang/AST/DeclNodes.inc:105
#129 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae6ae88) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#130 0x00007fffea4cd21e in clang::ASTImporter::ImportContext (this=0xa69af60, FromDC=0xae6aeb0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7234
#131 0x00007fffea4ccf25 in clang::ASTNodeImporter::ImportDeclParts (this=0x7ffffffee210, D=0xae6ad38, DC=@0x7ffffffee098: 0xa69afb0, LexicalDC=@0x7ffffffee090: 0xaf08fa0, Name=..., ToD=@0x7ffffffee078: 0x7ffffffee168, Loc=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1149
#132 0x00007fffea4e3cb3 in clang::ASTNodeImporter::VisitClassTemplateDecl (this=0x7ffffffee210, D=0xae6ad38) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4466
#133 0x00007fffea50bbdc in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffee210, D=0xae6ad38) at tools/clang/include/clang/AST/DeclNodes.inc:195
#134 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae6ad38) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#135 0x00007fffea4cb830 in clang::ASTImporter::Import (this=0xa69af60, From=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7453
#136 0x00007fffea4cb548 in clang::ASTNodeImporter::VisitTemplateSpecializationType (this=0x7ffffffee5d0, T=0xae6b380) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:984
#137 0x00007fffea50b318 in clang::TypeVisitor<clang::ASTNodeImporter, clang::QualType>::Visit (this=0x7ffffffee5d0, T=0xae6b380) at ../../git/llvm/tools/clang/include/clang/AST/TypeNodes.def:99
#138 0x00007fffea4c89a5 in clang::ASTImporter::Import (this=0xa69af60, FromT=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7145
#139 0x00007fffea4cbf29 in clang::ASTNodeImporter::VisitElaboratedType (this=0x7ffffffee780, T=0xae6b3d0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1014
#140 0x00007fffea50b28c in clang::TypeVisitor<clang::ASTNodeImporter, clang::QualType>::Visit (this=0x7ffffffee780, T=0xae6b3d0) at ../../git/llvm/tools/clang/include/clang/AST/TypeNodes.def:94
#141 0x00007fffea4c89a5 in clang::ASTImporter::Import (this=0xa69af60, FromT=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7145
#142 0x00007fffea4d2b2e in clang::ASTNodeImporter::VisitTypedefNameDecl (this=0x7ffffffeebe0, D=0xae6acc0, IsAlias=false) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1978
#143 0x00007fffea4d30af in clang::ASTNodeImporter::VisitTypedefDecl (this=0x7ffffffeebe0, D=0xae6acc0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2009
#144 0x00007fffea50bd48 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffeebe0, D=0xae6acc0) at tools/clang/include/clang/AST/DeclNodes.inc:303
#145 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae6acc0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#146 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7ffffffef140, FromDC=0x8d9c168, ForceImport=false, ToDC=0x0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#147 0x00007fffea4d208d in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7ffffffef140, D=0x8d9c140) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1879
#148 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffef140, D=0x8d9c140) at tools/clang/include/clang/AST/DeclNodes.inc:105
#149 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8d9c140) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#150 0x00007fffea4cc091 in clang::ASTImporter::Import (this=0xa69af60, FromNNS=0x8d9c248) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7340
#151 0x00007fffea4cbec6 in clang::ASTNodeImporter::VisitElaboratedType (this=0x7ffffffef320, T=0x8d9c300) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1009
#152 0x00007fffea50b28c in clang::TypeVisitor<clang::ASTNodeImporter, clang::QualType>::Visit (this=0x7ffffffef320, T=0x8d9c300) at ../../git/llvm/tools/clang/include/clang/AST/TypeNodes.def:94
#153 0x00007fffea4c89a5 in clang::ASTImporter::Import (this=0xa69af60, FromT=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7145
#154 0x00007fffea4d9e23 in clang::ASTNodeImporter::VisitFieldDecl (this=0x7ffffffef6e0, D=0xae6ac00) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2946
#155 0x00007fffea50be28 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7ffffffef6e0, D=0xae6ac00) at tools/clang/include/clang/AST/DeclNodes.inc:369
#156 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0xae6ac00) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#157 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7fffffff0150, FromDC=0x8cf9818, ForceImport=true, ToDC=0xafca1b0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#158 0x00007fffea4ceabe in clang::ASTNodeImporter::ImportDefinition (this=0x7fffffff0150, From=0x8cf97e0, To=0xafca178, Kind=clang::ASTNodeImporter::IDK_Default) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1413
#159 0x00007fffea4d6143 in clang::ASTNodeImporter::VisitRecordDecl (this=0x7fffffff0150, D=0x8cf97e0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2438
#160 0x00007fffea530b88 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::VisitCXXRecordDecl (this=0x7fffffff0150, D=0x8cf97e0) at tools/clang/include/clang/AST/DeclNodes.inc:251
#161 0x00007fffea50bca0 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7fffffff0150, D=0x8cf97e0) at tools/clang/include/clang/AST/DeclNodes.inc:251
#162 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8cf97e0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#163 0x00007fffea4d49db in clang::ASTNodeImporter::VisitRecordDecl (this=0x7fffffff07c0, D=0x8d9b5a0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2209
#164 0x00007fffea530b88 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::VisitCXXRecordDecl (this=0x7fffffff07c0, D=0x8d9b5a0) at tools/clang/include/clang/AST/DeclNodes.inc:251
#165 0x00007fffea50bca0 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7fffffff07c0, D=0x8d9b5a0) at tools/clang/include/clang/AST/DeclNodes.inc:251
#166 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8d9b5a0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#167 0x00007fffea4cf097 in clang::ASTNodeImporter::ImportDeclContext (this=0x7fffffff0d20, FromDC=0x8d941c8, ForceImport=false, ToDC=0x0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1243
#168 0x00007fffea4d208d in clang::ASTNodeImporter::VisitNamespaceDecl (this=0x7fffffff0d20, D=0x8d941a0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1879
#169 0x00007fffea50baa8 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7fffffff0d20, D=0x8d941a0) at tools/clang/include/clang/AST/DeclNodes.inc:105
#170 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8d941a0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#171 0x00007fffea4cd21e in clang::ASTImporter::ImportContext (this=0xa69af60, FromDC=0x8d941c8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7234
#172 0x00007fffea4ccf25 in clang::ASTNodeImporter::ImportDeclParts (this=0x7fffffff1570, D=0x8cf97e0, DC=@0x7fffffff13a8: 0x7fffea530713 <llvm::DenseMapIterator<clang::Decl*, clang::Decl*, llvm::DenseMapInfo<clang::Decl*>, llvm::detail::DenseMapPair<clang::Decl*, clang::Decl*>, false>::DenseMapIterator(llvm::detail::DenseMapPair<clang::Decl*, clang::Decl*>*, llvm::detail::DenseMapPair<clang::Decl*, clang::Decl*>*, llvm::DebugEpochBase const&, bool)+83>, LexicalDC=@0x7fffffff13a0: 0x7fffffff13e0, Name=..., ToD=@0x7fffffff1388: 0x7fffffff1508, Loc=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1149
#173 0x00007fffea4d4a92 in clang::ASTNodeImporter::VisitRecordDecl (this=0x7fffffff1570, D=0x8cf97e0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2221
#174 0x00007fffea530b88 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::VisitCXXRecordDecl (this=0x7fffffff1570, D=0x8cf97e0) at tools/clang/include/clang/AST/DeclNodes.inc:251
#175 0x00007fffea50bca0 in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7fffffff1570, D=0x8cf97e0) at tools/clang/include/clang/AST/DeclNodes.inc:251
#176 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8cf97e0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#177 0x00007fffea4cb017 in clang::ASTNodeImporter::VisitRecordType (this=0x7fffffff1690, T=0x8d9c0b0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:916
#178 0x00007fffea50b254 in clang::TypeVisitor<clang::ASTNodeImporter, clang::QualType>::Visit (this=0x7fffffff1690, T=0x8d9c0b0) at ../../git/llvm/tools/clang/include/clang/AST/TypeNodes.def:92
#179 0x00007fffea4c89a5 in clang::ASTImporter::Import (this=0xa69af60, FromT=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7145
#180 0x00007fffea4c990c in clang::ASTNodeImporter::VisitLValueReferenceType (this=0x7fffffff1820, T=0xade0c90) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:647
#181 0x00007fffea50afec in clang::TypeVisitor<clang::ASTNodeImporter, clang::QualType>::Visit (this=0x7fffffff1820, T=0xade0c90) at ../../git/llvm/tools/clang/include/clang/AST/TypeNodes.def:67
#182 0x00007fffea4c89a5 in clang::ASTImporter::Import (this=0xa69af60, FromT=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7145
#183 0x00007fffea4ca451 in clang::ASTNodeImporter::VisitFunctionProtoType (this=0x7fffffff1b60, T=0xade0d00) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:770
#184 0x00007fffea50b120 in clang::TypeVisitor<clang::ASTNodeImporter, clang::QualType>::Visit (this=0x7fffffff1b60, T=0xade0d00) at ../../git/llvm/tools/clang/include/clang/AST/TypeNodes.def:80
#185 0x00007fffea4c89a5 in clang::ASTImporter::Import (this=0xa69af60, FromT=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7145
#186 0x00007fffea4c97ac in clang::ASTNodeImporter::VisitPointerType (this=0x7fffffff1cf0, T=0xade1320) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:628
#187 0x00007fffea50afb4 in clang::TypeVisitor<clang::ASTNodeImporter, clang::QualType>::Visit (this=0x7fffffff1cf0, T=0xade1320) at ../../git/llvm/tools/clang/include/clang/AST/TypeNodes.def:64
#188 0x00007fffea4c89a5 in clang::ASTImporter::Import (this=0xa69af60, FromT=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7145
#189 0x00007fffea4ee1b2 in clang::ASTNodeImporter::VisitImplicitCastExpr (this=0x7fffffff1f40, E=0xade12d0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6088
#190 0x00007fffea50d427 in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7fffffff1f40, S=0xade12d0) at tools/clang/include/clang/AST/StmtNodes.inc:423
#191 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xade12d0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#192 0x00007fffea4c9eb5 in clang::ASTImporter::Import (this=0xa69af60, FromE=0xade12d0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7289
#193 0x00007fffea4f389e in clang::ASTNodeImporter::VisitCallExpr (this=0x7fffffff2300, E=0xade1348) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6807
#194 0x00007fffea50d2d7 in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7fffffff2300, S=0xade1348) at tools/clang/include/clang/AST/StmtNodes.inc:329
#195 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xade1348) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#196 0x00007fffea52aee7 in bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const (this=0x7fffffff23e0, From=0xade1348) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:472
#197 0x00007fffea52ae8a in std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) (__first=0xade1398, __last=0xade13b0, __result=0x7fffffff2548, __unary_op=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306
#198 0x00007fffea52adf0 in clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**> (this=0x7fffffff26a0, Ibegin=0xade1398, Iend=0xade13b0, Obegin=0x7fffffff2548) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:469
Python Exception <class 'gdb.error'> There is no member or method named Size.:
#199 0x00007fffea501d1c in clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> > (this=0x7fffffff26a0, InContainer=..., OutContainer=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:483
#200 0x00007fffea4e7abc in clang::ASTNodeImporter::VisitCompoundStmt (this=0x7fffffff26a0, S=0xade1388) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5149
#201 0x00007fffea50ce5e in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7fffffff26a0, S=0xade1388) at tools/clang/include/clang/AST/StmtNodes.inc:79
#202 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xade1388) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#203 0x00007fffea4e84f4 in clang::ASTNodeImporter::VisitIfStmt (this=0x7fffffff2910, S=0xade13f0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5235
#204 0x00007fffea50db7b in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7fffffff2910, S=0xade13f0) at tools/clang/include/clang/AST/StmtNodes.inc:849
#205 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xade13f0) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#206 0x00007fffea4e8581 in clang::ASTNodeImporter::VisitIfStmt (this=0x7fffffff2b80, S=0xade1890) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5239
#207 0x00007fffea50db7b in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7fffffff2b80, S=0xade1890) at tools/clang/include/clang/AST/StmtNodes.inc:849
#208 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xade1890) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#209 0x00007fffea52aee7 in bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const (this=0x7fffffff2c60, From=0xade1890) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:472
#210 0x00007fffea52ae8a in std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) (__first=0xade1938, __last=0xade1948, __result=0x7fffffff2de0, __unary_op=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306
#211 0x00007fffea52adf0 in clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**> (this=0x7fffffff2f20, Ibegin=0xade1920, Iend=0xade1948, Obegin=0x7fffffff2dc8) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:469
Python Exception <class 'gdb.error'> There is no member or method named Size.:
#212 0x00007fffea501d1c in clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> > (this=0x7fffffff2f20, InContainer=..., OutContainer=...) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:483
#213 0x00007fffea4e7abc in clang::ASTNodeImporter::VisitCompoundStmt (this=0x7fffffff2f20, S=0xade1910) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5149
#214 0x00007fffea50ce5e in clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit (this=0x7fffffff2f20, S=0xade1910) at tools/clang/include/clang/AST/StmtNodes.inc:79
#215 0x00007fffea4d3c93 in clang::ASTImporter::Import (this=0xa69af60, FromS=0xade1910) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7303
#216 0x00007fffea4d8e08 in clang::ASTNodeImporter::VisitFunctionDecl (this=0x7fffffff38b0, D=0x8da9e60) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2836
#217 0x00007fffea50be7c in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7fffffff38b0, D=0x8da9e60) at tools/clang/include/clang/AST/DeclNodes.inc:389
#218 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8da9e60) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#219 0x00007fffea4d8fcb in clang::ASTNodeImporter::VisitFunctionDecl (this=0x7fffffff41f0, D=0x8d13858) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2868
#220 0x00007fffea50be7c in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7fffffff41f0, D=0x8d13858) at tools/clang/include/clang/AST/DeclNodes.inc:389
#221 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8d13858) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#222 0x00007fffea4d71f2 in clang::ASTNodeImporter::VisitFunctionDecl (this=0x7fffffff4b30, D=0x8da9e60) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2602
#223 0x00007fffea50be7c in clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit (this=0x7fffffff4b30, D=0x8da9e60) at tools/clang/include/clang/AST/DeclNodes.inc:389
#224 0x00007fffea4c8640 in clang::ASTImporter::Import (this=0xa69af60, FromD=0x8da9e60) at ../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:7220
#225 0x00007fffe3cff040 in clang::cross_tu::CrossTranslationUnitContext::importDefinition (this=0x6b35c8, FD=0x8da9e60) at ../../git/llvm/tools/clang/lib/CrossTU/CrossTranslationUnit.cpp:338
#226 0x00007fffe3cfe483 in clang::cross_tu::CrossTranslationUnitContext::getCrossTUDefinition (this=0x6b35c8, FD=0x7626ca8, CrossTUDir="/home/egbomrt/WORK/CodeCheckerProjects/bitcoin/reports/ctu-dir/x86_64", IndexName="externalFnMap.txt", DisplayCTUProgress=true) at ../../git/llvm/tools/clang/lib/CrossTU/CrossTranslationUnit.cpp:250
#227 0x00007fffe37fa8b2 in clang::ento::AnyFunctionCall::getRuntimeDefinition (this=0x1c290b0) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CallEvent.cpp:390
#228 0x00007fffe389bf36 in clang::ento::ExprEngine::defaultEvalCall (this=0x7fffffff6ed0, Bldr=..., Pred=0x8bb87d8, CallTemplate=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp:915
#229 0x00007fffe3819183 in clang::ento::CheckerManager::runCheckersForEvalCall (this=0x6b3e80, Dst=..., Src=..., Call=..., Eng=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CheckerManager.cpp:619
#230 0x00007fffe389ad52 in clang::ento::ExprEngine::evalCall (this=0x7fffffff6ed0, Dst=..., Pred=0x8bb87d8, Call=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp:517
#231 0x00007fffe389ac08 in clang::ento::ExprEngine::VisitCallExpr (this=0x7fffffff6ed0, CE=0x7626dd8, Pred=0x8bb87d8, dst=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp:489
#232 0x00007fffe385a934 in clang::ento::ExprEngine::Visit (this=0x7fffffff6ed0, S=0x7626dd8, Pred=0x8bb87d8, DstTop=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:1305
#233 0x00007fffe3857641 in clang::ento::ExprEngine::ProcessStmt (this=0x7fffffff6ed0, S=..., Pred=0x8bb8768) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:566
#234 0x00007fffe38572fa in clang::ento::ExprEngine::processCFGElement (this=0x7fffffff6ed0, E=..., Pred=0x8bb8768, StmtIdx=4, Ctx=0x7fffffff69b8) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:410
#235 0x00007fffe383ab06 in clang::ento::CoreEngine::HandlePostStmt (this=0x7fffffff6ef0, B=0x84f8988, StmtIdx=4, Pred=0x8bb8768) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:531
#236 0x00007fffe383a406 in clang::ento::CoreEngine::dispatchWorkItem (this=0x7fffffff6ef0, Pred=0x8bb8768, Loc=..., WU=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:279
#237 0x00007fffe3839f68 in clang::ento::CoreEngine::ExecuteWorkList (this=0x7fffffff6ef0, L=0x1bfb040, Steps=195838, InitState=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:235
#238 0x00007fffe5553925 in clang::ento::ExprEngine::ExecuteWorkList (this=0x7fffffff6ed0, L=0x1bfb040, Steps=225000) at ../../git/llvm/tools/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h:114
#239 0x00007fffe54f41eb in (anonymous namespace)::AnalysisConsumer::ActionExprEngine (this=0x6b3560, D=0x1a1b790, ObjCGCEnabled=false, IMode=clang::ento::ExprEngine::Inline_Regular, VisitedCallees=0x7fffffff7588) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:720
#240 0x00007fffe54f3f81 in (anonymous namespace)::AnalysisConsumer::RunPathSensitiveChecks (this=0x6b3560, D=0x1a1b790, IMode=clang::ento::ExprEngine::Inline_Regular, Visited=0x7fffffff7588) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:741
#241 0x00007fffe54f3c35 in (anonymous namespace)::AnalysisConsumer::HandleCode (this=0x6b3560, D=0x1a1b790, Mode=2, IMode=clang::ento::ExprEngine::Inline_Regular, VisitedCallees=0x7fffffff7588) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:687
#242 0x00007fffe54e723e in (anonymous namespace)::AnalysisConsumer::HandleDeclsCallGraph (this=0x6b3560, LocalTUDeclsSize=884) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:500
#243 0x00007fffe54e54ad in (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit (this=0x6b3560, C=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:552
#244 0x00007fffe8705de6 in clang::ParseAST (S=..., PrintStats=false, SkipFunctionBodies=false) at ../../git/llvm/tools/clang/lib/Parse/ParseAST.cpp:159
#245 0x00007fffef06829c in clang::ASTFrontendAction::ExecuteAction (this=0x69df10) at ../../git/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:998
#246 0x00007fffef067d10 in clang::FrontendAction::Execute (this=0x69df10) at ../../git/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:897
#247 0x00007fffeefdcf1a in clang::CompilerInstance::ExecuteAction (this=0x6712e0, Act=...) at ../../git/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:991
#248 0x00007fffeeba3ce6 in clang::ExecuteCompilerInvocation (Clang=0x6712e0) at ../../git/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:252
#249 0x0000000000425649 in cc1_main (Argv=llvm::ArrayRef of length 342 = {...}, Argv0=0x7fffffffb4db "/home/egbomrt/WORK/llvm2/build/debug/bin/clang-6.0", MainAddr=0x415d70 <GetExecutablePath[abi:cxx11](char const*, bool)>) at ../../git/llvm/tools/clang/tools/driver/cc1_main.cpp:221
#250 0x0000000000418189 in ExecuteCC1Tool (argv=llvm::ArrayRef of length 344 = {...}, Tool="") at ../../git/llvm/tools/clang/tools/driver/driver.cpp:309
#251 0x0000000000416e8d in main (argc_=344, argv_=0x7fffffffa598) at ../../git/llvm/tools/clang/tools/driver/driver.cpp:388
```

### PR DESCRIPTION
**Pull request by martong**
The crux of the issue was that lookup could not find previous decls of
a friend class. The solution involves making the friend declarations
visible in their decl context (i.e. adding them to the lookup table).
This fix involves two other repairs:
(1) We could not handle the addition of injected class types properly
when a redecl chain was involved, now this is fixed.
(2) DeclContext::removeDecl failed if the lookup table in Vector form
did not contain the to be removed element. This caused troubles in
ASTImporter::ImportDeclContext. This is also fixed.

Fixes #484

### CODE REVIEW

**Comment by martong** [comment]
Unfortunately dos not fix #487 . Perhaps because there are other cases (other than broken redecl chains of classes) when structural equivalency does not match and thus an empty DeclGroup is created.

File: lib/AST/ASTImporter.cpp [hunk 1]
```diff
@@ -2431,7 +2449,7 @@ Decl *ASTNodeImporter::VisitRecordDecl(RecordDecl *D) {
     } else {
       if (GetImportedOrCreateDecl(D2, D, Importer.getToContext(),
                                   D->getTagKind(), DC, StartLoc, Loc,
-                                  Name.getAsIdentifierInfo(), PrevDecl))
```
Comment (martong) [inline lib/AST/ASTImporter.cpp]: This is a mistake here.

File: lib/Analysis/CFG.cpp [hunk 2]
```diff
@@ -2248,6 +2248,11 @@ CFGBlock *CFGBuilder::VisitConditionalOperator(AbstractConditionalOperator *C,
 }
 
 CFGBlock *CFGBuilder::VisitDeclStmt(DeclStmt *DS) {
+  //if (DS->isSingleDecl() && !DS->getSingleDecl())
```
Comment (martong) [inline lib/Analysis/CFG.cpp]: Should be part of another PR.

File: lib/Basic/SourceManager.cpp [hunk 3]
```diff
@@ -2061,6 +2061,7 @@ bool SourceManager::isBeforeInTranslationUnit(SourceLocation LHS,
       return LIsScratch;
     return LOffs.second < ROffs.second;
   }
+  return LB < RB;
```
Comment (martong) [inline lib/Basic/SourceManager.cpp]: Leftover from debug :(

File: unittests/AST/ASTImporterTest.cpp [hunk 4]
```diff
@@ -4120,6 +4184,100 @@ TEST_P(ImportVariables, InitAndDefinitionAreInTheFromContext) {
...
+      )",
+      Lang_CXX, "input1.cc");
+  Definition = FirstDeclMatcher<CXXRecordDecl>().match(
+      FromTU1, cxxRecordDecl(hasName("F")));
+  auto *Imported1 = Import(Definition, Lang_CXX);
+  EXPECT_TRUE(Imported1->getPreviousDecl());
+  EXPECT_EQ(Imported0, Imported1->getPreviousDecl());
+}
+
+// TODO test class template specializations too
```
Comment (martong) [inline unittests/AST/ASTImporterTest.cpp]: Leftover, sorry :(

File: lib/AST/ASTImporter.cpp [hunk 5]
```diff
@@ -2406,9 +2415,18 @@ Decl *ASTNodeImporter::VisitRecordDecl(RecordDecl *D) {
               break;
             }
           }
-          D2CXX->setTypeForDecl(nullptr);
-          Importer.getToContext().getInjectedClassNameType(D2CXX,
-              ToDescribed->getInjectedClassNameSpecialization());
+          // Create an injected type for the whole redecl chain.
+          SmallVector<Decl*, 2> Redecls = getCanonicalForwardRedeclChain(D2CXX);
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: SmallVector<Decl *, 2>

File: include/clang/AST/DeclContextInternals.h [hunk 6]
```diff
@@ -122,6 +122,13 @@ struct StoredDeclsList {
              == Vec.end() && "list still contains decl");
   }
 
+  bool containsInVector(NamedDecl* D) {
```
Comment (balazske) [inline include/clang/AST/DeclContextInternals.h]: `NamedDecl *D`

File: lib/AST/ASTImporter.cpp [hunk 7]
```diff
@@ -4549,18 +4569,24 @@ Decl *ASTNodeImporter::VisitClassTemplateDecl(ClassTemplateDecl *D) {
...
+
+  if (D->getDeclContext()->containsDeclAndLoad(D))
+    DC->addDeclInternal(D2);
+  if (DC != LexicalDC && D->getLexicalDeclContext()->containsDeclAndLoad(D))
     LexicalDC->addDeclInternal(D2);
 
+  if (FoundTemplate) {
+    auto *Recent =
+        const_cast<ClassTemplateDecl *>(FoundTemplate->getMostRecentDecl());
+    D2->setPreviousDecl(Recent);
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: I think the decl chains of template and templated Decls should match. Probably add assert here?
`Recent->getTemplatedDecl() == ToTemplated->getPreviousDecl()`

File: lib/AST/ASTImporter.cpp [hunk 8]
```diff
@@ -4480,17 +4498,19 @@ Decl *ASTNodeImporter::VisitClassTemplateDecl(ClassTemplateDecl *D) {
...
     SmallVector<NamedDecl *, 2> FoundDecls;
     DC->getRedeclContext()->localUncachedLookup(Name, FoundDecls);
     for (unsigned I = 0, N = FoundDecls.size(); I != N; ++I) {
-      if (!FoundDecls[I]->isInIdentifierNamespace(Decl::IDNS_Ordinary))
+      if (!FoundDecls[I]->isInIdentifierNamespace(Decl::IDNS_Ordinary | Decl::IDNS_TagFriend))
         continue;
 
       Decl *Found = FoundDecls[I];
-      if (auto *FoundTemplate = dyn_cast<ClassTemplateDecl>(Found)) {
+      if ((FoundTemplate = dyn_cast<ClassTemplateDecl>(Found))) {
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: Remove one level of unneeded `(` `)`.

File: unittests/AST/ASTImporterTest.cpp [hunk 9]
```diff
@@ -4032,6 +4062,40 @@ TEST_P(DeclContextTest, removeDeclOfClassTemplateSpecialization) {
...
+  // Investigate the list.
+  auto *DC = A0->getDeclContext();
+  ASSERT_TRUE(DC->containsDecl(A0));
+  ASSERT_TRUE(DC->containsDecl(A1));
+
+  // Investigate the lookup table.
+  auto *Map = DC->getLookupPtr();
+  ASSERT_TRUE(Map);
+  auto I = Map->find(A0->getDeclName());
+  ASSERT_FALSE(I == Map->end());
```
Comment (balazske) [inline unittests/AST/ASTImporterTest.cpp]: `ASSERT_EQ` ?

**Comment by martong** [comment]
Update: Changed the style where you indicated, and added an assert, in a new commit so you can follow the diff.

**Comment by balazske** [comment]
The code looks OK.
But in the tests it could be better to use descriptive names (not `Xxx0` and `Xxx1`) and not re-use existing variables with different meaning. (If not corrected here, this can be problem in the opensource review. My test code was not accepted with such problems once.)

**Comment by balazske** [comment]
Another thing: We can check if there are more similar tests that are not in the `ImportFriendClasses` fixture and move these in. (Similar issues may exist with other tests.)

File: lib/AST/ASTImporter.cpp (hunk 7 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp]: This assert was a very good idea, it revealed a mistake I made, working on fixing that.

**Comment by martong** [comment]
Update: changed the PR to properly build up the redecl chain not just in case of Friends.
Now this seems to fix #487 too.
I am going to create additional tests as well.

File: lib/AST/ASTImporter.cpp [hunk 10]
```diff
@@ -2281,35 +2282,30 @@ Decl *ASTNodeImporter::VisitRecordDecl(RecordDecl *D) {
...
-            Importer.MapImported(D, FoundDef);
-            if (const auto *DCXX = dyn_cast<CXXRecordDecl>(D)) {
-              auto *FoundCXX = dyn_cast<CXXRecordDecl>(FoundDef);
-              assert(FoundCXX && "Record type mismatch");
-
-              if (D->isCompleteDefinition() && !Importer.isMinimalImport())
-                // FoundDef may not have every implicit method that D has
-                // because implicit methods are created only if they are used.
-                ImportImplicitMethods(DCXX, FoundCXX);
+          if (D->isThisDeclarationADefinition()) {
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: `isThisDeclarationADefinition` and `isCompleteDefinition` return the same value. Something can be simplified here?

Comment (martong) [reply lib/AST/ASTImporter.cpp]: Good point, thanks.

Comment (martong) [reply lib/AST/ASTImporter.cpp]: This part is really messy so would be very good if we could simplify somehow.

File: lib/AST/ASTImporter.cpp [hunk 11]
```diff
@@ -2282,52 +2282,28 @@ Decl *ASTNodeImporter::VisitRecordDecl(RecordDecl *D) {
...
+            return FoundDef;
           }
-        } else if (!D->isCompleteDefinition()) {
-          // We have a forward declaration of this type in the "From" context,
-          // we have to hook that to the redecl chain.
-          if (FoundRecord->hasExternalLexicalStorage() &&
-              !FoundRecord->isCompleteDefinition())
-            FoundRecord->getASTContext().getExternalSource()->CompleteType(FoundRecord);
-          if (D->hasExternalLexicalStorage())
-            D->getASTContext().getExternalSource()->CompleteType(D);
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp:2317]: Are the `CompleteType` calls not needed?

File: lib/AST/ASTImporter.cpp [hunk 12]
```diff
@@ -2273,67 +2274,43 @@ Decl *ASTNodeImporter::VisitRecordDecl(RecordDecl *D) {
...
-        if (!SearchName) {
+        // Do not emit false positive diagnostic in case of unnamed
+        // struct/union and in case of anonymous structs.  Would be false
+        // becasue there may be several anonymous/unnamed structs in a class.
+        // E.g. these are both valid:
+        //  struct A { // unnamed structs
+        //    struct { struct A *next; } entry0;
+        //    struct { struct A *next; } entry1;
+        //  };
+        //  struct X { struct { int a; }; struct { int b; }; // anon structs
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: A `}` (close of `X`) is missing from comment above.

File: lib/AST/ASTImporter.cpp (hunk 11 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp:2317]: We already completed `D` in line 2255.
And `FoundRecord` must had been completed either during it's import or it is created by the parser and don't have external lexical storage.

File: lib/AST/ASTImporter.cpp (hunk 12 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp]: Thanks, good point.

File: unittests/AST/ASTImporterTest.cpp [hunk 13]
```diff
@@ -4087,6 +4087,305 @@ TEST_P(ImportVariables, InitAndDefinitionAreInTheFromContext) {
...
+  EXPECT_EQ(DeclCounter<CXXRecordDecl>().match(ToTU, Pattern), 2u);
+  auto ToProto = FirstDeclMatcher<CXXRecordDecl>().match(ToTU, Pattern);
+  auto ToDef = LastDeclMatcher<CXXRecordDecl>().match(ToTU, Pattern);
+  EXPECT_TRUE(ImportedDef == ToDef);
+  EXPECT_TRUE(ImportedProto == ToProto);
+  EXPECT_TRUE(ToDef->isThisDeclarationADefinition());
+  EXPECT_FALSE(ToProto->isThisDeclarationADefinition());
+  EXPECT_EQ(ToDef->getPreviousDecl(), ToProto);
+}
+
```
Comment (balazske) [inline unittests/AST/ASTImporterTest.cpp:4224]: Good tests.

File: unittests/AST/ASTImporterTest.cpp [hunk 14]
```diff
@@ -4087,6 +4087,305 @@ TEST_P(ImportVariables, InitAndDefinitionAreInTheFromContext) {
...
+  auto FromD = FirstDeclMatcher<ClassTemplateDecl>().match(FromTU, Pattern);
+
+  Decl *ImportedD = Import(FromD, Lang_CXX);
+  Decl *ToTU = ImportedD->getTranslationUnitDecl();
+
+  EXPECT_EQ(DeclCounter<ClassTemplateDecl>().match(ToTU, Pattern), 1u);
+  auto ToD = LastDeclMatcher<ClassTemplateDecl>().match(ToTU, Pattern);
+  EXPECT_TRUE(ImportedD == ToD);
+  EXPECT_FALSE(ToD->isThisDeclarationADefinition());
+  EXPECT_TRUE(ToD->getTemplatedDecl());
```
Comment (balazske) [inline unittests/AST/ASTImporterTest.cpp]: This check is not needed or is needed as the first check. It is not "normal" that there is no `getTemplatedDecl` (`isThisDeclarationADefinition` calls also getTemplatedDecl).

Comment (martong) [reply unittests/AST/ASTImporterTest.cpp]: Ok, good point, I moved them upwards and made the check to be an `ASSERT_`.

**Review by balazske — APPROVED** [review]

**Comment by martong** [comment]
ctu-clang7:
 https://github.com/Ericsson/clang/commit/9d42ac3de0e1292ad018d12fd4ef57d803e42f25

**Comment by martong** [comment]
https://reviews.llvm.org/D53655
