### PR TITLE
Spaces in source files were not handled properly. Now this is fixed.

### LINKED ISSUE #122: handle spaces in filename in externalfnmap.txt

### PR DESCRIPTION
**Pull request by dkrupp**
Fixes #122

### CODE REVIEW

File: lib/AST/ASTContext.cpp [hunk 1]
```diff
@@ -1494,12 +1494,16 @@ const FunctionDecl *ASTContext::getCTUDefinition(
...
-      SmallString<128> ExternalFunctionMap = CTUDir;
+      SmallString<256> ExternalFunctionMap = CTUDir;
       llvm::sys::path::append(ExternalFunctionMap, "externalFnMap.txt");
       std::ifstream ExternalFnMapFile(ExternalFunctionMap.c_str());
       std::string FunctionName, FileName;
-      while (ExternalFnMapFile >> FunctionName >> FileName) {
-        SmallString<128> FilePath = CTUDir;
+      std::string line;
+      while (std::getline(ExternalFnMapFile, line)) {
+        size_t pos=line.find(" ");
```
Comment (Xazax-hun) [inline lib/AST/ASTContext.cpp]: Clang format this snippet.

File: lib/AST/ASTContext.cpp [hunk 2]
```diff
@@ -1494,12 +1494,16 @@ const FunctionDecl *ASTContext::getCTUDefinition(
...
+        FunctionName=line.substr(0,pos);
+        FileName=line.substr(pos+1, std::string::npos );
```
Comment (Xazax-hun) [inline lib/AST/ASTContext.cpp]: The second argument is redundant.

File: tools/ctu-analysis/ctu-build.py [hunk 3]
```diff
@@ -192,7 +187,7 @@ def create_external_fn_maps(ctuindir):
     for filename in files:
         with open(filename, 'rb') as in_file:
             for line in in_file:
-                mangled_name, ast_file = line.strip().split(' ')
+                mangled_name, ast_file = line.strip().split(' ',1)
```
Comment (Xazax-hun) [inline tools/ctu-analysis/ctu-build.py]: Comma after space.

File: tools/ctu-analysis/ctu-build.py [hunk 4]
```diff
@@ -139,34 +139,30 @@ def generate_ast(params):
...
     ast_command.append('-w')
     ast_command.append(source)
     ast_command.append('-o')
     ast_command.append(ast_path)
-    ast_command_str = ' '.join(dir_command) + " && " + ' '.join(ast_command)
-    logging.info(ast_command_str)
-    subprocess.call(ast_command_str, shell=True)
+    os.chdir(directory)
+    logging.info(ast_command)
+    subprocess.call(ast_command, shell=False)
```
Comment (gerazo) [inline tools/ctu-analysis/ctu-build.py]: This may be easier with cwd=directory instead of doing a separate chdir

File: tools/ctu-analysis/ctu-build.py [hunk 5]
```diff
@@ -139,34 +139,30 @@ def generate_ast(params):
...
-    funcmap_command_str = ' '.join(dir_command) + \
-                          " && " + ' '.join(funcmap_command)
-    logging.info("Calling function map: " + funcmap_command_str)
+    funcmap_command.extend(args)    
     output = []
-    fn_out = subprocess.check_output(funcmap_command_str, shell=True)
+    os.chdir(directory);
+    logging.info("map_functions: ")
+    logging.info(funcmap_command)
+    fn_out = subprocess.check_output(funcmap_command)
```
Comment (gerazo) [inline tools/ctu-analysis/ctu-build.py]: Also cwd=... would be better here.

Comment (gerazo) [inline tools/ctu-analysis/ctu-build.py]: Have you tried some of our old projects with escape problem prone constructions? I think changing shell=True from shell=False can have an influence on escaping the whole command line, so we can screw up some stuff. I think openssl was heavily affected by the escaping problem.

**Comment by dkrupp** [comment]
tests on openssl works. added some extra tests in the tools/ctu-analysis/tests directory
