### PR TITLE
Merge ValueKind of InitListExpr

### LINKED ISSUE #469: ValueKind of InitListExpr is not imported
The following test fails:
```
TEST_P(ASTImporterTestBase, ExprValueKindShouldBeImported) {
  Decl *TU = getTuDecl(
      R"(
      const int &init();
      void foo() { const int &a{init()}; }
      )", Lang_CXX11, "input0.cc");
  auto *FromD = FirstDeclMatcher<VarDecl>().match(TU, varDecl(hasName("a")));
  ASSERT_TRUE(FromD->getAnyInitializer());
  auto *InitExpr = FromD->getAnyInitializer();
  ASSERT_TRUE(InitExpr);
  ASSERT_TRUE(InitExpr->isGLValue());

  auto *ToD = Import(FromD, Lang_CXX11);
  ASSERT_TRUE(ToD);
  auto *ToInitExpr = cast<VarDecl>(ToD)->getAnyInitializer();
  ASSERT_TRUE(ToInitExpr);
  EXPECT_TRUE(ToInitExpr->isGLValue());
}
```

This results a CSA 'llvm_unreachable' assertion to fire (in radiosw): `'Assume' not implemented for this NonLoc`
Since the value kind is not imported, the analyzer engine believes that the given `InitListExpr` is an rvalue, thus it creates a `nonloc::CompoundVal` instead of creating memory region (as in case of an lvalue reference).

### PR DESCRIPTION
**Pull request by martong**
Fixes #469

### CODE REVIEW

File: unittests/AST/ASTImporterTest.cpp [hunk 1]
```diff
@@ -3897,6 +3897,25 @@ TEST_P(ASTImporterTestBase, ClassTemplateFullAndPartialSpecsShouldNotBeMixed) {
...
+  ASSERT_TRUE(InitExpr);
+  ASSERT_TRUE(InitExpr->isGLValue());
+
+  auto *ToD = Import(FromD, Lang_CXX11);
+  ASSERT_TRUE(ToD);
+  auto *ToInitExpr = cast<VarDecl>(ToD)->getAnyInitializer();
+  ASSERT_TRUE(ToInitExpr);
+  EXPECT_TRUE(ToInitExpr->isGLValue());
+}
+
```
Comment (balazske) [inline unittests/AST/ASTImporterTest.cpp:3918]: Theoretically not only ValueKind but all other fields should be checked.

Comment (martong) [reply unittests/AST/ASTImporterTest.cpp:3918]: Yes, I agree, but I really don't know how to synthesize tests for the other properties.
