### PR TITLE
Fix recursive function with prototype

### LINKED ISSUE #282: AST merge of recursive function
file `recursive.h`:
```
#pragma once
void recursive_function();
```

file `recursive.cpp`:
```
#include "recursive.h"
void recursive_function() {
	recursive_function();
}
```

file `root.cpp`:
```
#include "recursive.h"
void root() {
	recursive_function();
}

```
following commands produce the crash below:

`clang -cc1 -emit-pch -o recursive.ast recursive.cpp`
`clang -cc1 -ast-merge recursive.ast -fsyntax-only root.cpp`
```
Unsortable locations found
UNREACHABLE executed at llvm/tools/clang/lib/Basic/SourceManager.cpp:2057!
#0 0x00007f7753a64fd9 llvm::sys::PrintStackTrace(llvm::raw_ostream&) llvm/lib/Support/Unix/Signals.inc:398:0
#1 0x00007f7753a6506a PrintStackTraceSignalHandler(void*) llvm/lib/Support/Unix/Signals.inc:462:0
#2 0x00007f7753a634b0 llvm::sys::RunSignalHandlers() llvm/lib/Support/Signals.cpp:49:0
#3 0x00007f7753a64971 SignalHandler(int) llvm/lib/Support/Unix/Signals.inc:252:0
#4 0x00007f775037dcb0 (/lib/x86_64-linux-gnu/libc.so.6+0x36cb0)
#5 0x00007f775037dc37 gsignal /build/eglibc-ripdx6/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#6 0x00007f7750381028 abort /build/eglibc-ripdx6/eglibc-2.19/stdlib/abort.c:91:0
#7 0x00007f77539a9331 bindingsErrorHandler(void*, std::string const&, bool) llvm/lib/Support/ErrorHandling.cpp:198:0
#8 0x00007f77528fd24e clang::SourceManager::isBeforeInTranslationUnit(clang::SourceLocation, clang::SourceLocation) const llvm/tools/clang/lib/Basic/SourceManager.cpp:2058:0
#9 0x00007f774924bd4e (anonymous namespace)::CompareOverloadCandidatesForDisplay::operator()(clang::OverloadCandidate const*, clang::OverloadCandidate const*) llvm/tools/clang/lib/Sema/SemaOverload.cpp:10340:0
#10 0x00007f774925dd2c void std::__insertion_sort<clang::OverloadCandidate**, (anonymous namespace)::CompareOverloadCandidatesForDisplay>(clang::OverloadCandidate**, clang::OverloadCandidate**, (anonymous namespace)::CompareOverloadCandidatesForDisplay) /usr/include/c++/4.8/bits/stl_algo.h:2159:0
#11 0x00007f774925cf16 void std::__final_insertion_sort<clang::OverloadCandidate**, (anonymous namespace)::CompareOverloadCandidatesForDisplay>(clang::OverloadCandidate**, clang::OverloadCandidate**, (anonymous namespace)::CompareOverloadCandidatesForDisplay) /usr/include/c++/4.8/bits/stl_algo.h:2232:0
#12 0x00007f774925c448 void std::sort<clang::OverloadCandidate**, (anonymous namespace)::CompareOverloadCandidatesForDisplay>(clang::OverloadCandidate**, clang::OverloadCandidate**, (anonymous namespace)::CompareOverloadCandidatesForDisplay) /usr/include/c++/4.8/bits/stl_algo.h:5502:0
#13 0x00007f774924c54d clang::OverloadCandidateSet::NoteCandidates(clang::Sema&, clang::OverloadCandidateDisplayKind, llvm::ArrayRef<clang::Expr*>, llvm::StringRef, clang::SourceLocation, llvm::function_ref<bool (clang::OverloadCandidate&)>) llvm/tools/clang/lib/Sema/SemaOverload.cpp:10452:0
#14 0x00007f7749251bfa FinishOverloadedCallExpr(clang::Sema&, clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, clang::OverloadCandidateSet*, clang::OverloadCandidate**, clang::OverloadingResult, bool) llvm/tools/clang/lib/Sema/SemaOverload.cpp:11787:0
#15 0x00007f77492520a6 clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) llvm/tools/clang/lib/Sema/SemaOverload.cpp:11855:0
#16 0x00007f7748f5eb86 clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool) llvm/tools/clang/lib/Sema/SemaExpr.cpp:5190:0
#17 0x00007f7749f4568b clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) llvm/tools/clang/lib/Parse/ParseExpr.cpp:1664:0
#18 0x00007f7749f442d8 clang::Parser::ParseCastExpression(bool, bool, bool&, clang::Parser::TypeCastState, bool) llvm/tools/clang/lib/Parse/ParseExpr.cpp:1429:0
#19 0x00007f7749f3ff8a clang::Parser::ParseCastExpression(bool, bool, clang::Parser::TypeCastState, bool) llvm/tools/clang/lib/Parse/ParseExpr.cpp:525:0
#20 0x00007f7749f3ea88 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) llvm/tools/clang/lib/Parse/ParseExpr.cpp:170:0
#21 0x00007f7749f3e880 clang::Parser::ParseExpression(clang::Parser::TypeCastState) llvm/tools/clang/lib/Parse/ParseExpr.cpp:120:0
#22 0x00007f7749f99d58 clang::Parser::ParseExprStatement() llvm/tools/clang/lib/Parse/ParseStmt.cpp:413:0
#23 0x00007f7749f9954d clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) llvm/tools/clang/lib/Parse/ParseStmt.cpp:224:0
#24 0x00007f7749f98f06 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::AllowedConstructsKind, clang::SourceLocation*) llvm/tools/clang/lib/Parse/ParseStmt.cpp:111:0
#25 0x00007f7749f9bfc9 clang::Parser::ParseCompoundStatementBody(bool) llvm/tools/clang/lib/Parse/ParseStmt.cpp:1001:0
#26 0x00007f7749f9f6f6 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) llvm/tools/clang/lib/Parse/ParseStmt.cpp:1967:0
#27 0x00007f7749fbd28b clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) llvm/tools/clang/lib/Parse/Parser.cpp:1212:0
#28 0x00007f7749ef7db1 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, unsigned int, clang::SourceLocation*, clang::Parser::ForRangeInit*) llvm/tools/clang/lib/Parse/ParseDecl.cpp:1953:0
#29 0x00007f7749fbc288 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) llvm/tools/clang/lib/Parse/Parser.cpp:980:0
#30 0x00007f7749fbc34d clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) llvm/tools/clang/lib/Parse/Parser.cpp:995:0
#31 0x00007f7749fbbaa4 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) llvm/tools/clang/lib/Parse/Parser.cpp:845:0
#32 0x00007f7749fbae49 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) llvm/tools/clang/lib/Parse/Parser.cpp:613:0
#33 0x00007f7749edef30 clang::ParseAST(clang::Sema&, bool, bool) llvm/tools/clang/lib/Parse/ParseAST.cpp:146:0
#34 0x00007f7751009866 clang::ASTFrontendAction::ExecuteAction() llvm/tools/clang/lib/Frontend/FrontendAction.cpp:1005:0
#35 0x00007f7750f3da29 clang::ASTMergeAction::ExecuteAction() llvm/tools/clang/lib/Frontend/ASTMerge.cpp:78:0
#36 0x00007f77510092d7 clang::FrontendAction::Execute() llvm/tools/clang/lib/Frontend/FrontendAction.cpp:906:0
#37 0x00007f7750f99361 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:981:0
#38 0x00007f7750a95d32 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:251:0
#39 0x000000000044a4b8 (clang+0x44a4b8)
#40 0x0000000000440254 (clang+0x440254)
#41 0x0000000000440e52 (clang+0x440e52)
#42 0x00007f7750368f45 __libc_start_main /build/eglibc-ripdx6/eglibc-2.19/csu/libc-start.c:321:0
#43 0x000000000043dae9 (clang+0x43dae9)
Stack dump:
0.	Program arguments: clang -cc1 -ast-merge rf.ast -fsyntax-only root.cpp 
1.	root.cpp:3:21: current parser token ')'
2.	root.cpp:2:13: parsing function body 'root'
3.	root.cpp:2:13: in compound statement ('{}')
Aborted
```

### PR DESCRIPTION
**Pull request by martong**
This is the second attempt to fix #282

### CODE REVIEW

File: lib/AST/ASTImporter.cpp [hunk 1]
```diff
@@ -2362,10 +2351,9 @@ Decl *ASTNodeImporter::VisitFunctionDecl(FunctionDecl *D) {
         if (FoundFunction->hasExternalFormalLinkage() &&
             D->hasExternalFormalLinkage()) {
           if (IsStructuralMatch(D, FoundFunction)) {
-            // FIXME: Actually try to merge the body and other attributes.
             const FunctionDecl *FromBodyDecl = nullptr;
             D->hasBody(FromBodyDecl);
-            if (D == FromBodyDecl && !FoundFunction->hasBody()) {
+            if (FromBodyDecl && !FoundFunction->hasBody()) {
```
Comment (Xazax-hun) [inline lib/AST/ASTImporter.cpp]: Maybe using `hasBody` without passing a pointer is sufficient?

File: unittests/AST/ASTImporterTest.cpp [hunk 2]
```diff
@@ -1622,13 +1623,49 @@ TEST_F(ImportFunctions,
...
+  auto Pattern = cxxMethodDecl(hasName("f"), hasParent(cxxRecordDecl(hasName("D"))));
+  Decl *FromTU = getTuDecl(Code, Lang_CXX);
+  CXXMethodDecl *Proto = FirstDeclMatcher<CXXMethodDecl>().match(FromTU, Pattern);
+
+  ASSERT_EQ(Proto->size_overridden_methods(), 1u);
+  CXXMethodDecl* To = cast<CXXMethodDecl>(Import(Proto, Lang_CXX));
+  EXPECT_EQ(To->size_overridden_methods(), 1u);
+}
+
+TEST_F(ImportFunctions,
```
Comment (balazske) [inline unittests/AST/ASTImporterTest.cpp]: probably add such test not only for the `virtual` flag?

Comment (martong) [reply unittests/AST/ASTImporterTest.cpp]: We could do that, but I am not sure which flags to check. We had a problem in the previous fix particularly with the virtual flag.

Comment (balazske) [reply unittests/AST/ASTImporterTest.cpp]: Does this test code compile?
Should not `Fixture` be used instead of `ImportFunctions`?

Comment (martong) [reply unittests/AST/ASTImporterTest.cpp]: `ImportFunctions` came in with commit https://github.com/Ericsson/clang/pull/290/commits/81a877fbc4bd6f0665e17fc313e485967080a0d1

File: lib/AST/ASTImporter.cpp [hunk 3]
```diff
@@ -2559,7 +2545,18 @@ Decl *ASTNodeImporter::VisitFunctionDecl(FunctionDecl *D) {
...
+  const FunctionDecl* FromDefinition = nullptr;
+  if (Stmt *FromBody = D->getBody(FromDefinition)) {
+
+    // If we have the defintion in the FromCtx, mark that as imported.
+    // This handles difficulties when we have a recursive function with a
+    // prototype and a definition in the same ToCtx.  E.g. importing the
+    // prototype below would import the definition twice without this.
+    // "void f(); void f() { f(); }"
+    // This is because in the definition the CallExpression refers to the
+    // definition, not to the prototype.
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: This check should be inserted:
```
    if (!Importer.GetAlreadyImportedOrNull(
          const_cast<FunctionDecl*>(FromDefinition)))
```

File: lib/AST/ASTImporter.cpp [hunk 4]
```diff
@@ -2559,7 +2545,18 @@ Decl *ASTNodeImporter::VisitFunctionDecl(FunctionDecl *D) {
...
+    Importer.Imported(const_cast<FunctionDecl*>(FromDefinition), ToFunction);
```
Comment (Xazax-hun) [inline lib/AST/ASTImporter.cpp]: This line introduces the following assert (and it is very frequent):
```
clang-6.0: ../tools/clang/lib/AST/ASTImporter.cpp:7465: virtual clang::Decl* clang::ASTImporter::Imported(clang::Decl*, clang::Decl*): Assertion `(Pos == ImportedDecls.end() || Pos->second == To) && "Try to import an already imported Decl"' failed.
#0 0x00007f01a28b001a llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/egborho/OSLLVM/build/../lib/Support/Unix/Signals.inc:402:0
#1 0x00007f01a28addbe llvm::sys::RunSignalHandlers() /home/egborho/OSLLVM/build/../lib/Support/Signals.cpp:50:0
#2 0x00007f01a28adf32 SignalHandler(int) /home/egborho/OSLLVM/build/../lib/Support/Unix/Signals.inc:242:0
#3 0x00007f01a12574b0 (/lib/x86_64-linux-gnu/libc.so.6+0x354b0)
#4 0x00007f01a1257428 gsignal /build/glibc-Cl5G7W/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
#5 0x00007f01a125902a abort /build/glibc-Cl5G7W/glibc-2.23/stdlib/abort.c:91:0
#6 0x00007f01a124fbd7 __assert_fail_base /build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:92:0
#7 0x00007f01a124fc82 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc82)
#8 0x00007f019fa42b40 clang::ASTImporter::Imported(clang::Decl*, clang::Decl*) /home/egborho/OSLLVM/build/../tools/clang/lib/AST/ASTImporter.cpp:7479:0
#9 0x00007f019fa454d7 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egborho/OSLLVM/build/../tools/clang/lib/AST/ASTImporter.cpp:2575:0
#10 0x00007f019fa45d0f clang::ASTImporter::Import(clang::Decl*) /home/egborho/OSLLVM/build/../tools/clang/lib/AST/ASTImporter.cpp:6826:0
```

Maybe we should first check if we already imported the function definition and only attempt to import it if we did not import it yet?

File: lib/AST/ASTImporter.cpp (hunk 3 above)
Comment (Xazax-hun) [reply lib/AST/ASTImporter.cpp]: Oh, as far as I can see we noticed this almost the same time :)

File: lib/AST/ASTImporter.cpp (hunk 4 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp]: Actually, the if which Balazs suggests would solve this. That way we would first check if we already imported the function definition and only attempt to **mark that as imported** if we did not import it yet?

Comment (balazske) [reply lib/AST/ASTImporter.cpp]: This means the syntax tree will be manipulated to some extent (this was the case already). The actual definition of the function can be merged with other declarations. (The `FromDefinition` node will not imported any more because it is marked already as imported without really importing it.)

Comment (martong) [reply lib/AST/ASTImporter.cpp]: Yes, that is right. I believe this is because we don't want to have redundant nodes in the AST. Imagine a TU with a prototype and another TU with the same prototype; if we import from both we still want to have only one prototype. If a definition is available, then we import the definition immediately. So the AST will not be the same as literally merging the ASTs. I think the current `ImportFunctions` test cases demonstrate it quite well how do want to eliminate redundancies.
