### PR TITLE
Fix VarDecl Import

### LINKED ISSUE #477: VarDecl init expr and definition is not imported properly
The init expression of a VarDecl is overwritten in the "To" context if we import a VarDecl without an init expression (and with a definition).
The following unittest fails:
```
TEST_P(ASTImporterTestBase,
       Maci) {
  auto StructA =
      R"(
      struct A {
        static const int a = 1 + 2;
      };
      )";
  Decl *ToTU = getToTuDecl(StructA, Lang_CXX);
  Decl *FromTU =
      getTuDecl(std::string(StructA) + "const int A::a;", Lang_CXX, "input1.cc");

  auto *FromD0 = FirstDeclMatcher<VarDecl>().match(FromTU, varDecl(hasName("a"))); // Decl with init
  auto *FromD1 = LastDeclMatcher<VarDecl>().match(FromTU, varDecl(hasName("a"))); // Decl with definition
  ASSERT_EQ(FromD0, FromD1->getPreviousDecl());
  ASSERT_TRUE(FromD0->getInit());
  ASSERT_FALSE(FromD0->isThisDeclarationADefinition());
  ASSERT_TRUE(FromD1->isThisDeclarationADefinition());
  ASSERT_FALSE(FromD1->getInit());

  auto *ToD = FirstDeclMatcher<VarDecl>().match(ToTU, varDecl(hasName("a"))); // Decl with init
  ASSERT_TRUE(ToD->getInit());
  ASSERT_FALSE(ToD->getDefinition());

  auto *ImportedD = cast<VarDecl>(Import(FromD1, Lang_CXX11));
  EXPECT_TRUE(ImportedD->getAnyInitializer());
  EXPECT_TRUE(ImportedD->getDefinition());
  //EXPECT_TRUE(false);
}
```

### PR DESCRIPTION
**Pull request by martong**
Fixes #477

### CODE REVIEW

File: lib/AST/ASTImporter.cpp [hunk 1]
```diff
@@ -3291,9 +3293,11 @@ Decl *ASTNodeImporter::VisitVarDecl(VarDecl *D) {
...
-  // Templated declarations should never appear in the enclosing DeclContext.
-  if (!D->getDescribedVarTemplate())
-    LexicalDC->addDeclInternal(ToVar);
+  if (MergeWithVar) {
+    auto *Recent = const_cast<VarDecl *>(MergeWithVar->getMostRecentDecl());
+    updateAttrAndFlags(D, MergeWithVar);
+    ToVar->setPreviousDecl(Recent);
+  }
 
   // Merge the initializer.
```
Comment (martong) [inline lib/AST/ASTImporter.cpp]: This is not a "merge" rather an import.

File: unittests/AST/ASTImporterTest.cpp [hunk 2]
```diff
@@ -3983,6 +3983,93 @@ TEST_P(DeclContextTest, removeDeclOfClassTemplateSpecialization) {
...
+  auto *FromD1 = LastDeclMatcher<VarDecl>().match(
+      FromTU, varDecl(hasName("a"))); // Decl with definition
+  ASSERT_NE(FromD0, FromD1);
+
+  auto *ToD0 = cast<VarDecl>(Import(FromD0, Lang_CXX11));
+  auto *ToD1 = cast<VarDecl>(Import(FromD1, Lang_CXX11));
+  ASSERT_TRUE(ToD0);
+  ASSERT_TRUE(ToD1);
+  EXPECT_NE(ToD0, ToD1);
+  EXPECT_EQ(ToD1->getPreviousDecl() ,ToD0);
```
Comment (balazske) [inline unittests/AST/ASTImporterTest.cpp]: Better variable names can be used: `FromDWithInit`, `FromDWithDef` and similar.

File: lib/AST/ASTImporter.cpp [hunk 3]
```diff
@@ -1421,13 +1423,22 @@ bool ASTNodeImporter::ImportDefinition(VarDecl *From, VarDecl *To,
   if (To->getAnyInitializer())
     return false;
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp:1423]: Really this function does not ensure the definition, only the initializer? (If "definition" is not the same as initializer.)

File: lib/AST/ASTImporter.cpp [hunk 4]
```diff
@@ -3291,9 +3293,11 @@ Decl *ASTNodeImporter::VisitVarDecl(VarDecl *D) {
   ToVar->setAccess(D->getAccess());
   ToVar->setLexicalDeclContext(LexicalDC);
 
-  // Templated declarations should never appear in the enclosing DeclContext.
-  if (!D->getDescribedVarTemplate())
-    LexicalDC->addDeclInternal(ToVar);
+  if (MergeWithVar) {
+    auto *Recent = const_cast<VarDecl *>(MergeWithVar->getMostRecentDecl());
+    updateAttrAndFlags(D, MergeWithVar);
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: The `updateAttrAndFlags` is used to update data (from `D`) in the found Decl. I think this should be called at the `MapImported` cases (line 3223 and 3229).

File: lib/AST/ASTImporter.cpp [hunk 5]
```diff
@@ -3178,8 +3199,8 @@ Decl *ASTNodeImporter::VisitVarDecl(VarDecl *D) {
 
   // Try to find a variable in our own ("to") context with the same name and
   // in the same context as the variable we're importing.
+  VarDecl *MergeWithVar = nullptr;
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: This should be renamed to `ExistingVar` or similar.

File: lib/AST/ASTImporter.cpp (hunk 3 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp:1423]: Yes, the definition may be independent from the initializer.
Perhaps a better name would be just `ImportInitializer`.

File: unittests/AST/ASTImporterTest.cpp (hunk 2 above)
Comment (martong) [reply unittests/AST/ASTImporterTest.cpp]: Yes, good point.

File: lib/AST/ASTImporter.cpp (hunk 4 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp]: Ok, changed that.

Comment (martong) [reply lib/AST/ASTImporter.cpp]: This will not work that way. Just tried and moved `updateAttrAndFlags` before the MapImported calls, and the unit test which test the used flag fails.
If we think about it this is logical, since we should update the used flag when we do create a new VarDecl, and that is happening once we reach to this line. 
In those lines you mentioned (line 3223 and 3229) we do not create any new declaration, thus there is nothing to update.

File: lib/AST/ASTImporter.cpp (hunk 5 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp]: Renamed to `FoundByLookup`, since that is how we call it in `VisitFunctionDecl` too.

File: lib/AST/ASTImporter.cpp (hunk 3 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp:1423]: Renamed to `ImportInitializer`.

**Comment by martong** [comment]
Added a new commit, so you can easily track what changed, before merge I'll squash.

File: lib/AST/ASTImporter.cpp (hunk 4 above)
Comment (balazske) [reply lib/AST/ASTImporter.cpp]: Probably include it in both places? At create the used flag should be copied anyway. If an imported Decl is mapped to an existing, the imported may have the used flag set but the existing not, in this case the update is needed. Probably this case does not occur any more in the unit test because way of importing has changed (but the unit test originally was made to test the case when there is an existing `VarDecl` and an imported `VarDecl` is mapped to that and the used flag should be updated).

Comment (martong) [reply lib/AST/ASTImporter.cpp]: Okay, makes sense, I am going to check that and also the test.

File: lib/AST/ASTImporter.cpp [hunk 6]
```diff
@@ -3194,7 +3213,22 @@ Decl *ASTNodeImporter::VisitVarDecl(VarDecl *D) {
...
           if (Importer.IsStructurallyEquivalent(D->getType(),
                                                 FoundVar->getType())) {
-            MergeWithVar = FoundVar;
+
+            // The VarDecl in the "From" context has a definition, but in the
+            // "To" context we already has a definition.
+            VarDecl *FoundDef = FoundVar->getDefinition();
+            if (D->isThisDeclarationADefinition() && FoundDef) {
+              return Importer.MapImported(D, FoundDef);
+            }
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: Is there no problem with update of initializer? If the `D` is definition and has initializer, and the found has no initializer, it is not updated. (But theoretically the variable can have only one definition, so the definition of `D` should be the same as the found one, with initializer.)

Comment (martong) [reply lib/AST/ASTImporter.cpp]: Hmm, good point, but I don't think that could be a problem exactly because what you have written in the parentheses.
I would not merge the initializer. Intstead, we could diagnose an ODR error here if we see that the two definitions have different initializers, I added a FIXME for that.

File: lib/AST/ASTImporter.cpp (hunk 4 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp]: So, I've written two new test cases which exercises those cases. And indeed it is needed to add `updateAttrAndFlags` there.
Then I realized that we have to do this always after we found an existing decl or even if we created a new one.
This seems like a general rule, so I added the call of `updateAttrAndFlags` into `Import::(Decl*)`.

File: lib/AST/ASTImporter.cpp [hunk 7]
```diff
@@ -3211,11 +3246,11 @@ Decl *ASTNodeImporter::VisitVarDecl(VarDecl *D) {
                 return nullptr;
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp:3246]: I am not sure if this array type import is needed with the new code. The `FoundVar` is updated (`setType`) but later we create a new `VarDecl` instead (and if a new VarDecl is created it should contain all new information, the existing should not be changed, no "merge" is done).
In line 3239 the `getToContext` is used with `D` that is in the `FromContext`, is this correct?

**Comment by martong** [comment]
run tests

**Comment by martong** [comment]
run tests

File: lib/AST/ASTImporter.cpp (hunk 7 above)
Comment (martong) [reply lib/AST/ASTImporter.cpp:3246]: Yes, I agree, this comes from the "From" context.
Also, I created a new issue to revisit this code: https://github.com/Ericsson/clang/issues/485

File: unittests/AST/ASTImporterTest.cpp [hunk 8]
```diff
@@ -3100,6 +3100,55 @@ TEST_P(ASTImporterTestBase, ImportDoesUpdateUsedFlag) {
...
+  {
+    Decl *ToTU = getToTuDecl("int x = 1;", Lang_CXX);
+    ExistingD = FirstDeclMatcher<VarDecl>().match(ToTU, Pattern);
+  }
+  EXPECT_FALSE(ExistingD->isUsed(false));
+  {
+    Decl *FromTU = getTuDecl(
+        "int x = 1; int f() { return x; }", Lang_CXX, "input1.cc");
+    auto *FromD =
+        FirstDeclMatcher<FunctionDecl>().match(FromTU, functionDecl());
```
Comment (balazske) [inline unittests/AST/ASTImporterTest.cpp]: This is good if we are sure that there is not any other hidden generated function in `FromTU`. Better is to match always with name.

Comment (martong) [reply unittests/AST/ASTImporterTest.cpp]: Good catch, thank you.

**Review by balazske — APPROVED** [review]

**Comment by martong** [comment]
Update: squashed the commits into one.

**Comment by martong** [comment]
https://reviews.llvm.org/D51597
