### PR TITLE
Fix display ctu progress

### LINKED ISSUE #365: Ctu progress reports loaded AST files multiple times (Clang6 only)
E.g. in protobuf `field_comparator.cc` the log is duplicated for `message.cc`
```
± ag "loaded ast for source file" stderr                                                           --- COMMAND ---
1:ANALYZE (CTU loaded AST for source file): /home/egbomrt/WORK/CodeCheckerProjects/protobuf/src/google/protobuf/arena.cc
15:ANALYZE (CTU loaded AST for source file): /home/egbomrt/WORK/CodeCheckerProjects/protobuf/src/google/protobuf/stubs/common.cc
33:ANALYZE (CTU loaded AST for source file): /home/egbomrt/WORK/CodeCheckerProjects/protobuf/src/google/protobuf/stubs/once.cc
34:ANALYZE (CTU loaded AST for source file): /home/egbomrt/WORK/CodeCheckerProjects/protobuf/src/google/protobuf/message.cc
79:ANALYZE (CTU loaded AST for source file): /home/egbomrt/WORK/CodeCheckerProjects/protobuf/src/google/protobuf/message.cc
80:ANALYZE (CTU loaded AST for source file): /home/egbomrt/WORK/CodeCheckerProjects/protobuf/src/google/protobuf/descriptor.cc
```

### PR DESCRIPTION
**Pull request by martong**
Fixes #365

### CODE REVIEW

**Comment by martong** [comment]
We have to emit the message only when the file is physically loaded. Currently we emit even if we get the `Unit` from the cache `FileASTUnitMap`.

File: include/clang/CrossTU/CrossTranslationUnit.h [hunk 1]
```diff
@@ -126,7 +126,8 @@ class CrossTranslationUnitContext {
   /// Note that the AST files should also be in the \p CrossTUDir.
   llvm::Expected<ASTUnit *> loadExternalAST(StringRef LookupName,
                                             StringRef CrossTUDir,
-                                            StringRef IndexName);
+                                            StringRef IndexName,
+                                            bool DisplayCTUProgress);
```
Comment (Xazax-hun) [inline include/clang/CrossTU/CrossTranslationUnit.h]: Maybe having a default false argument would be useful.

**Comment by martong** [comment]
Update: Added a default arg.
