### PR TITLE
Template function import fixes

### LINKED ISSUE #176: OpenCV CTU analysis crash
The results of an OpenCV cross-tu analysis:

histogram.cpp:
```
should always be wrapped in ArrayToPointerDecay
UNREACHABLE executed at /home/gamesh411/Projects/ericsson/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:2291!
#0 0x00000000012ccac4 PrintStackTraceSignalHandler(void*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x12ccac4)
#1 0x00000000012cce16 SignalHandler(int) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x12cce16)
#2 0x00007fa9e249d670 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11670)
#3 0x00007fa9e100177f gsignal /build/glibc-mXZSwJ/glibc-2.24/signal/../sysdeps/unix/sysv/linux/raise.c:58:0
#4 0x00007fa9e100337a abort /build/glibc-mXZSwJ/glibc-2.24/stdlib/abort.c:91:0
#5 0x000000000128beeb (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x128beeb)
#6 0x000000000221a0c1 clang::ento::ExprEngine::VisitMemberExpr(clang::MemberExpr const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x221a0c1)
#7 0x0000000002214709 clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2214709)
#8 0x000000000220f8cf clang::ento::ExprEngine::ProcessStmt(clang::CFGStmt, clang::ento::ExplodedNode*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x220f8cf)
#9 0x000000000220f590 clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x220f590)
#10 0x0000000002204d51 clang::ento::CoreEngine::HandlePostStmt(clang::CFGBlock const*, unsigned int, clang::ento::ExplodedNode*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2204d51)
#11 0x0000000002203f4f clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2203f4f)
#12 0x0000000002015fb1 (anonymous namespace)::AnalysisConsumer::ActionExprEngine(clang::Decl*, bool, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2015fb1)
#13 0x0000000002015b5b (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2015b5b)
#14 0x000000000200f022 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x200f022)
#15 0x00000000022ffc16 clang::ParseAST(clang::Sema&, bool, bool) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x22ffc16)
#16 0x000000000180d188 clang::FrontendAction::Execute() (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x180d188)
#17 0x00000000017d0f41 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x17d0f41)
#18 0x0000000001897040 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x1897040)
#19 0x000000000077ecad cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x77ecad)
#20 0x000000000077d12a main (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x77d12a)
#21 0x00007fa9e0fec3f1 __libc_start_main /build/glibc-mXZSwJ/glibc-2.24/csu/../csu/libc-start.c:325:0
#22 0x000000000077a5ca _start (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x77a5ca)
Stack dump:
0.      Program arguments: /home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0 -cc1 -triple x86_64-unknown-linux-gnu -analyze -disable-free -main-file-name histogram.cpp -analyzer-store=region -analyzer-opt-analyze-nested-blocks -analyzer-eagerly-assume -analyzer-output plist -w -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-feature +sse -target-feature +sse2 -target-feature +sse3 -dwarf-column-info -debugger-tuning=gdb -ffunction-sections -coverage-notes-file /home/gamesh411/.codechecker/reports/clangsa_histogram.cpp_62dee806.gcno -resource-dir /home/gamesh411/Projects/ericsson/build/release/lib/clang/6.0.0 -D CVAPI_EXPORTS -D _USE_MATH_DEFINES -D __OPENCV_BUILD=1 -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -I /home/gamesh411/static_analysis/build/3rdparty/ippicv/ippicv_lnx/include -I /home/gamesh411/static_analysis/build/3rdparty/ippicv/ippiw_lnx/include -I /home/gamesh411/static_analysis/build -I /home/gamesh411/static_analysis/opencv/modules/imgproc/include -I /home/gamesh411/static_analysis/opencv/modules/imgproc/src -I /home/gamesh411/static_analysis/build/modules/imgproc -I /home/gamesh411/static_analysis/opencv/modules/core/include -I /usr/include/c++/6 -I /usr/include/x86_64-linux-gnu/c++/6 -I /usr/include/c++/6/backward -I /usr/local/include -I /home/gamesh411/Projects/ericsson/build/release/lib/clang/6.0.0/include -I /usr/include/x86_64-linux-gnu -I /usr/include -D DEBUG -D _DEBUG -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/backward -internal-isystem /usr/local/include -internal-isystem /home/gamesh411/Projects/ericsson/build/release/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-long-long -fdeprecated-macro -fdebug-compilation-dir /home/gamesh411/static_analysis/build -ferror-limit 19 -fmessage-length 0 -fvisibility hidden -fvisibility-inlines-hidden -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -analyzer-opt-analyze-headers -analyzer-output=plist-multi-file -analyzer-disable-checker alpha.clone.CloneChecker -analyzer-disable-checker alpha.core.BoolAssignment -analyzer-disable-checker alpha.core.CallAndMessageUnInitRefArg -analyzer-disable-checker alpha.core.CastSize -analyzer-disable-checker alpha.core.CastToStruct -analyzer-disable-checker alpha.core.Conversion -analyzer-disable-checker alpha.core.DynamicTypeChecker -analyzer-disable-checker alpha.core.FixedAddr -analyzer-disable-checker alpha.core.IdenticalExpr -analyzer-disable-checker alpha.core.PointerArithm -analyzer-disable-checker alpha.core.PointerSub -analyzer-disable-checker alpha.core.SizeofPtr -analyzer-disable-checker alpha.core.TestAfterDivZero -analyzer-disable-checker alpha.cplusplus.IteratorRange -analyzer-disable-checker alpha.cplusplus.MisusedMovedObject -analyzer-disable-checker alpha.deadcode.UnreachableCode -analyzer-disable-checker alpha.osx.cocoa.DirectIvarAssignment -analyzer-disable-checker alpha.osx.cocoa.DirectIvarAssignmentForAnnotatedFunctions -analyzer-disable-checker alpha.osx.cocoa.InstanceVariableInvalidation -analyzer-disable-checker alpha.osx.cocoa.MissingInvalidationMethod -analyzer-disable-checker alpha.osx.cocoa.localizability.PluralMisuseChecker -analyzer-disable-checker alpha.security.ArrayBound -analyzer-disable-checker alpha.security.ArrayBoundV2 -analyzer-disable-checker alpha.security.MallocOverflow -analyzer-disable-checker alpha.security.ReturnPtrRange -analyzer-disable-checker alpha.security.taint.TaintPropagation -analyzer-disable-checker alpha.unix.BlockInCriticalSection -analyzer-disable-checker alpha.unix.Chroot -analyzer-disable-checker alpha.unix.PthreadLock -analyzer-disable-checker alpha.unix.SimpleStream -analyzer-disable-checker alpha.unix.Stream -analyzer-disable-checker alpha.unix.cstring.BufferOverlap -analyzer-disable-checker alpha.unix.cstring.NotNullTerminated -analyzer-disable-checker alpha.unix.cstring.OutOfBounds -analyzer-disable-checker apiModeling.google.GTest -analyzer-checker=core.CallAndMessage -analyzer-checker=core.DivideZero -analyzer-checker=core.DynamicTypePropagation -analyzer-checker=core.NonNullParamChecker -analyzer-checker=core.NullDereference -analyzer-checker=core.StackAddressEscape -analyzer-checker=core.UndefinedBinaryOperatorResult -analyzer-checker=core.VLASize -analyzer-checker=core.builtin.BuiltinFunctions -analyzer-checker=core.builtin.NoReturnFunctions -analyzer-checker=core.uninitialized.ArraySubscript -analyzer-checker=core.uninitialized.Assign -analyzer-checker=core.uninitialized.Branch -analyzer-checker=core.uninitialized.CapturedBlockVariable -analyzer-checker=core.uninitialized.UndefReturn -analyzer-checker=cplusplus.NewDelete -analyzer-checker=cplusplus.NewDeleteLeaks -analyzer-checker=cplusplus.SelfAssignment -analyzer-checker=deadcode.DeadStores -analyzer-disable-checker debug.AnalysisOrder -analyzer-disable-checker debug.ConfigDumper -analyzer-disable-checker debug.DumpBugHash -analyzer-disable-checker debug.DumpCFG -analyzer-disable-checker debug.DumpCallGraph -analyzer-disable-checker debug.DumpCalls -analyzer-disable-checker debug.DumpDominators -analyzer-disable-checker debug.DumpLiveVars -analyzer-disable-checker debug.DumpTraversal -analyzer-disable-checker debug.ExprInspection -analyzer-disable-checker debug.Stats -analyzer-disable-checker debug.TaintTest -analyzer-disable-checker debug.ViewCFG -analyzer-disable-checker debug.ViewCallGraph -analyzer-disable-checker debug.ViewExplodedGraph -analyzer-disable-checker llvm.Conventions -analyzer-disable-checker nullability.NullPassedToNonnull -analyzer-disable-checker nullability.NullReturnedFromNonnull -analyzer-disable-checker nullability.NullableDereferenced -analyzer-disable-checker nullability.NullablePassedToNonnull -analyzer-disable-checker nullability.NullableReturnedFromNonnull -analyzer-disable-checker optin.cplusplus.VirtualCall -analyzer-disable-checker optin.mpi.MPI-Checker -analyzer-disable-checker optin.osx.cocoa.localizability.EmptyLocalizationContextChecker -analyzer-disable-checker optin.osx.cocoa.localizability.NonLocalizedStringChecker -analyzer-disable-checker optin.performance.Padding -analyzer-disable-checker optin.portability.UnixAPI -analyzer-disable-checker osx.API -analyzer-disable-checker osx.NumberObjectConversion -analyzer-disable-checker osx.ObjCProperty -analyzer-disable-checker osx.SecKeychainAPI -analyzer-disable-checker osx.cocoa.AtSync -analyzer-disable-checker osx.cocoa.ClassRelease -analyzer-disable-checker osx.cocoa.Dealloc -analyzer-disable-checker osx.cocoa.IncompatibleMethodTypes -analyzer-disable-checker osx.cocoa.Loops -analyzer-disable-checker osx.cocoa.MissingSuperCall -analyzer-disable-checker osx.cocoa.NSAutoreleasePool -analyzer-disable-checker osx.cocoa.NSError -analyzer-disable-checker osx.cocoa.NilArg -analyzer-disable-checker osx.cocoa.NonNilReturnValue -analyzer-disable-checker osx.cocoa.ObjCGenerics -analyzer-disable-checker osx.cocoa.RetainCount -analyzer-disable-checker osx.cocoa.SelfInit -analyzer-disable-checker osx.cocoa.SuperDealloc -analyzer-disable-checker osx.cocoa.UnusedIvars -analyzer-disable-checker osx.cocoa.VariadicMethodTypes -analyzer-disable-checker osx.coreFoundation.CFError -analyzer-disable-checker osx.coreFoundation.CFNumber -analyzer-disable-checker osx.coreFoundation.CFRetainRelease -analyzer-disable-checker osx.coreFoundation.containers.OutOfBounds -analyzer-disable-checker osx.coreFoundation.containers.PointerSizedValues -analyzer-disable-checker security.FloatLoopCounter -analyzer-checker=security.insecureAPI.UncheckedReturn -analyzer-checker=security.insecureAPI.getpw -analyzer-checker=security.insecureAPI.gets -analyzer-checker=security.insecureAPI.mkstemp -analyzer-checker=security.insecureAPI.mktemp -analyzer-disable-checker security.insecureAPI.rand -analyzer-disable-checker security.insecureAPI.strcpy -analyzer-checker=security.insecureAPI.vfork -analyzer-checker=unix.API -analyzer-checker=unix.Malloc -analyzer-checker=unix.MallocSizeof -analyzer-checker=unix.MismatchedDeallocator -analyzer-checker=unix.StdCLibraryFunctions -analyzer-checker=unix.Vfork -analyzer-checker=unix.cstring.BadSizeArg -analyzer-checker=unix.cstring.NullArg -analyzer-disable-checker valist.CopyToSelf -analyzer-disable-checker valist.Uninitialized -analyzer-disable-checker valist.Unterminated -o /home/gamesh411/.codechecker/reports/clangsa_histogram.cpp_62dee806.plist -x c++ /home/gamesh411/static_analysis/opencv/modules/imgproc/src/histogram.cpp 
1.      <eof> parser at end of file
2.      While analyzing stack: 
        #0 void cvNormalizeHist(CvHistogram *hist, double factor) __attribute__((visibility("default")))
        #1 void cvCalcArrBackProjectPatch(CvArr **arr, CvArr *dst, CvSize patch_size, CvHistogram *hist, int method, double norm_factor) __attribute__((visibility("default")))
3.      /home/gamesh411/static_analysis/opencv/modules/imgproc/src/histogram.cpp:2981:15: Error evaluating statement
4.      /home/gamesh411/static_analysis/opencv/modules/imgproc/src/histogram.cpp:2981:15: Error evaluating statement
clang-6.0: error: unable to execute command: Aborted (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (https://github.com/Ericsson/clang 4b38271e218709c82a843ba340e3cdbabbdfd8f2) (https://github.com/llvm-mirror/llvm 0472b1ccd49cc2737cc35037829371eb9cdbc07c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/gamesh411/ctu_release/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-6.0: note: diagnostic msg: /tmp/histogram-5fcbcd.cpp
clang-6.0: note: diagnostic msg: /tmp/histogram-5fcbcd.sh
clang-6.0: note: diagnostic msg:
```

The immediate cause of the crash is the same for the other 2 files:
quadsubpix.cpp:
```
should always be wrapped in ArrayToPointerDecay
UNREACHABLE executed at /home/gamesh411/Projects/ericsson/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:2291!
#0 0x00000000012ccac4 PrintStackTraceSignalHandler(void*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x12ccac4)
#1 0x00000000012cce16 SignalHandler(int) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x12cce16)
#2 0x00007f60d0b9b670 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11670)
#3 0x00007f60cf6ff77f gsignal /build/glibc-mXZSwJ/glibc-2.24/signal/../sysdeps/unix/sysv/linux/raise.c:58:0
#4 0x00007f60cf70137a abort /build/glibc-mXZSwJ/glibc-2.24/stdlib/abort.c:91:0
#5 0x000000000128beeb (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x128beeb)
#6 0x000000000221a0c1 clang::ento::ExprEngine::VisitMemberExpr(clang::MemberExpr const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x221a0c1)
#7 0x0000000002214709 clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2214709)
#8 0x000000000220f8cf clang::ento::ExprEngine::ProcessStmt(clang::CFGStmt, clang::ento::ExplodedNode*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x220f8cf)
#9 0x000000000220f590 clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x220f590)
#10 0x0000000002204d51 clang::ento::CoreEngine::HandlePostStmt(clang::CFGBlock const*, unsigned int, clang::ento::ExplodedNode*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2204d51)
#11 0x0000000002203f4f clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2203f4f)
#12 0x0000000002015fb1 (anonymous namespace)::AnalysisConsumer::ActionExprEngine(clang::Decl*, bool, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2015fb1)
#13 0x0000000002015b5b (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2015b5b)
#14 0x000000000200f022 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x200f022)
#15 0x00000000022ffc16 clang::ParseAST(clang::Sema&, bool, bool) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x22ffc16)
#16 0x000000000180d188 clang::FrontendAction::Execute() (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x180d188)
#17 0x00000000017d0f41 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x17d0f41)
#18 0x0000000001897040 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x1897040)
#19 0x000000000077ecad cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x77ecad)
#20 0x000000000077d12a main (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x77d12a)
#21 0x00007f60cf6ea3f1 __libc_start_main /build/glibc-mXZSwJ/glibc-2.24/csu/../csu/libc-start.c:325:0
#22 0x000000000077a5ca _start (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x77a5ca)
```

```
1.      <eof> parser at end of file
2.      While analyzing stack: 
        #0 static int segment_hist_max(const cv::Mat &hist, int &low_thresh, int &high_thresh)
        #1 bool cv::find4QuadCornerSubpix(cv::InputArray _img, cv::InputOutputArray _corners, cv::Size region_size) __attribute__((visibility("default")))
3.      /home/gamesh411/static_analysis/opencv/modules/calib3d/src/quadsubpix.cpp:121:24: Error evaluating statement
4.      /home/gamesh411/static_analysis/opencv/modules/calib3d/src/quadsubpix.cpp:121:24: Error evaluating statement
```

and test_fundam.cpp:
```
should always be wrapped in ArrayToPointerDecay
UNREACHABLE executed at /home/gamesh411/Projects/ericsson/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:2291!
#0 0x00000000012ccac4 PrintStackTraceSignalHandler(void*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x12ccac4)
#1 0x00000000012cce16 SignalHandler(int) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x12cce16)
#2 0x00007f9eac073670 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11670)
#3 0x00007f9eaabd777f gsignal /build/glibc-mXZSwJ/glibc-2.24/signal/../sysdeps/unix/sysv/linux/raise.c:58:0
#4 0x00007f9eaabd937a abort /build/glibc-mXZSwJ/glibc-2.24/stdlib/abort.c:91:0
#5 0x000000000128beeb (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x128beeb)
#6 0x000000000221a0c1 clang::ento::ExprEngine::VisitMemberExpr(clang::MemberExpr const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x221a0c1)
#7 0x0000000002214709 clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2214709)
#8 0x000000000220f8cf clang::ento::ExprEngine::ProcessStmt(clang::CFGStmt, clang::ento::ExplodedNode*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x220f8cf)
#9 0x000000000220f590 clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x220f590)
#10 0x0000000002204d51 clang::ento::CoreEngine::HandlePostStmt(clang::CFGBlock const*, unsigned int, clang::ento::ExplodedNode*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2204d51)
#11 0x0000000002203f4f clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2203f4f)
#12 0x0000000002015fb1 (anonymous namespace)::AnalysisConsumer::ActionExprEngine(clang::Decl*, bool, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2015fb1)
#13 0x0000000002015b5b (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x2015b5b)
#14 0x000000000200f022 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x200f022)
#15 0x00000000022ffc16 clang::ParseAST(clang::Sema&, bool, bool) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x22ffc16)
#16 0x000000000180d188 clang::FrontendAction::Execute() (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x180d188)
#17 0x00000000017d0f41 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x17d0f41)
#18 0x0000000001897040 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x1897040)
#19 0x000000000077ecad cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x77ecad)
#20 0x000000000077d12a main (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x77d12a)
#21 0x00007f9eaabc23f1 __libc_start_main /build/glibc-mXZSwJ/glibc-2.24/csu/../csu/libc-start.c:325:0
#22 0x000000000077a5ca _start (/home/gamesh411/Projects/ericsson/build/release/bin/clang-6.0+0x77a5ca)
```

```
1.      <eof> parser at end of file
2.      While analyzing stack: 
        #0 int cvTsRodrigues(const CvMat *src, CvMat *dst, CvMat *jacobian)
        #1 void cvtest::Rodrigues(const cv::Mat &src, cv::Mat &dst, cv::Mat *jac = 0)
        #2 void CV_EssentialMatTest::fill_array(int test_case_idx, int i, int j, cv::Mat &arr)
3.      /home/gamesh411/static_analysis/opencv/modules/calib3d/test/test_fundam.cpp:231:15: Error evaluating statement
4.      /home/gamesh411/static_analysis/opencv/modules/calib3d/test/test_fundam.cpp:231:15: Error evaluating statement
```

### PR DESCRIPTION
**Pull request by szepet**
Fixing importing template functions and methods problems. Fixes #176 .

### CODE REVIEW

File: test/Analysis/xtu-main_usr.cpp [hunk 1]
```diff
@@ -76,4 +85,9 @@ int main() {
 
   clang_analyzer_eval(fun_using_type_alias_template() == 3); // expected-warning{{TRUE}}
   clang_analyzer_eval(fun_using_pack_expansion() == 4); // expected-warning{{TRUE}}
+
+  // Note: the analysis of template function is not supported yet.
+  Ptr p;
+  clang_analyzer_eval(p.a<void>() == 1);       // expected-warning{{UNKNOWN}}
```
Comment (Xazax-hun) [inline test/Analysis/xtu-main_usr.cpp]: This is surprising. Why is it not supported? Where is the limitation?

**Comment by Xazax-hun** [comment]
Please squash some of your commits and add more meaningful messages.

File: lib/AST/ASTStructuralEquivalence.cpp [hunk 2]
```diff
@@ -1210,6 +1210,45 @@ static bool IsStructurallyEquivalent(StructuralEquivalenceContext &Context,
   if (!::IsStructurallyEquivalent(Context, D1->getType(), D2->getType()))
     return false;
 
+  if (D1->getDescribedFunctionTemplate()) {
+    if (D2->getDescribedFunctionTemplate()) {
+      if (!Context.IsStructurallyEquivalent(D1->getDescribedFunctionTemplate(),
```
Comment (Xazax-hun) [inline lib/AST/ASTStructuralEquivalence.cpp]: Maybe you could rewrite this as `return ...`and eliminate an if?

File: unittests/AST/ASTImporterTest.cpp [hunk 3]
```diff
@@ -495,6 +495,22 @@ TEST(ImportDecl, ImportFunctionTemplateDecl) {
...
+      "template<typename Y> int a() { return 1; }"
+      "template<typename Y, typename D> int a(){ return 2; }"
+      "void declToImport() { a<void>(); }",
+      Lang_CXX, "", Lang_CXX, Verifier,
+      functionDecl(has(compoundStmt(has(callExpr(has(ignoringParenImpCasts(
+          declRefExpr(to(functionDecl(hasBody(compoundStmt(
+              has(returnStmt(has(integerLiteral(equals(1)))))))))))))))))));
+  EXPECT_TRUE(testImport(
+      "template<typename Y> int a() { return 1; }"
+      "template<typename Y, typename D> int a(){ return 2; }"
```
Comment (Xazax-hun) [inline unittests/AST/ASTImporterTest.cpp]: This snippet is not following the clang formatting rules. Missing space before brace.

File: lib/AST/ASTImporter.cpp [hunk 4]
```diff
@@ -141,6 +141,7 @@ namespace clang {
                            bool Complain = true);
     bool IsStructuralMatch(EnumDecl *FromEnum, EnumDecl *ToRecord,
                            bool Complain = true);
+    bool IsStructuralMatch(FunctionDecl *From, FunctionDecl *To);
```
Comment (Xazax-hun) [inline lib/AST/ASTImporter.cpp]: I wonder if it is a good pattern to have that many functions that do the same thing. In the future maybe this would be a great candidate to be refactored (i.e.: one templated implementation).

File: test/Analysis/xtu-main_usr.cpp (hunk 1 above)
Comment (Xazax-hun) [reply test/Analysis/xtu-main_usr.cpp]: In the meantime, we discovered the reason, and code snippets like this should not happen in the checked codebase.

File: lib/AST/ASTStructuralEquivalence.cpp (hunk 2 above)
Comment (szepet) [reply lib/AST/ASTStructuralEquivalence.cpp]: I don't think its a good idea since this way the function can be extended without modification of this code snippet.

File: unittests/AST/ASTImporterTest.cpp (hunk 3 above)
Comment (szepet) [reply unittests/AST/ASTImporterTest.cpp]: Done.
