### PR TITLE
ASTImporter::Imported - VisitFunctionTemplateDecl assertion fix

### LINKED ISSUE #311: VisitFunctionTemplateDecl related "already imported" assertion
```
clang-5.0: llvm/tools/clang/lib/AST/ASTImporter.cpp:7433: virtual clang::Decl* clang::ASTImporter::Imported(clang::Decl*, clang::Decl*): Assertion `(Pos == ImportedDecls.end() || Pos->second == To) && "Try to import an already imported Decl"' failed.
#0 0x00007f5506daafd9 llvm::sys::PrintStackTrace(llvm::raw_ostream&) llvm/lib/Support/Unix/Signals.inc:398:0
#1 0x00007f5506dab06a PrintStackTraceSignalHandler(void*) llvm/lib/Support/Unix/Signals.inc:462:0
#2 0x00007f5506da94b0 llvm::sys::RunSignalHandlers() llvm/lib/Support/Signals.cpp:49:0
#3 0x00007f5506daa971 SignalHandler(int) llvm/lib/Support/Unix/Signals.inc:252:0
#4 0x00007f55036c3cb0 (/lib/x86_64-linux-gnu/libc.so.6+0x36cb0)
#5 0x00007f55036c3c37 gsignal /build/eglibc-ripdx6/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#6 0x00007f55036c7028 abort /build/eglibc-ripdx6/eglibc-2.19/stdlib/abort.c:91:0
#7 0x00007f55036bcbf6 __assert_fail_base /build/eglibc-ripdx6/eglibc-2.19/assert/assert.c:92:0
#8 0x00007f55036bcca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#9 0x00007f54ff320d73 clang::ASTImporter::Imported(clang::Decl*, clang::Decl*) llvm/tools/clang/lib/AST/ASTImporter.cpp:7433:0
#10 0x00007f54ff311182 clang::ASTNodeImporter::VisitFunctionTemplateDecl(clang::FunctionTemplateDecl*) llvm/tools/clang/lib/AST/ASTImporter.cpp:4629:0
#11 0x00007f54ff331647 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) build/tools/clang/include/clang/AST/DeclNodes.inc:201:0
#12 0x00007f54ff31e30f clang::ASTImporter::Import(clang::Decl*) llvm/tools/clang/lib/AST/ASTImporter.cpp:6793:0
#13 0x00007f54ff2fe52f clang::ASTNodeImporter::ImportDeclContext(clang::DeclContext*, bool, clang::DeclContext*) llvm/tools/clang/lib/AST/ASTImporter.cpp:1070:0
#14 0x00007f54ff2ff4f3 clang::ASTNodeImporter::ImportDefinition(clang::RecordDecl*, clang::RecordDecl*, clang::ASTNodeImporter::ImportDefinitionKind) llvm/tools/clang/lib/AST/ASTImporter.cpp:1219:0
#15 0x00007f54ff30fb74 clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl(clang::ClassTemplateSpecializationDecl*) llvm/tools/clang/lib/AST/ASTImporter.cpp:4360:0
#16 0x00007f54ff339775 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::VisitClassTemplatePartialSpecializationDecl(clang::ClassTemplatePartialSpecializationDecl*) build/tools/clang/include/clang/AST/DeclNodes.inc:259:0
#17 0x00007f54ff331707 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) build/tools/clang/include/clang/AST/DeclNodes.inc:259:0
#18 0x00007f54ff31e30f clang::ASTImporter::Import(clang::Decl*) llvm/tools/clang/lib/AST/ASTImporter.cpp:6793:0
#19 0x00007f54ff2fe52f clang::ASTNodeImporter::ImportDeclContext(clang::DeclContext*, bool, clang::DeclContext*) llvm/tools/clang/lib/AST/ASTImporter.cpp:1070:0
#20 0x00007f54ff30146f clang::ASTNodeImporter::VisitNamespaceDecl(clang::NamespaceDecl*) llvm/tools/clang/lib/AST/ASTImporter.cpp:1673:0
...

### PR DESCRIPTION
**Pull request by balazske**
Fix for assertion
"Try to import an already imported Decl"
that occurs through calling
ASTNodeImporter::VisitFunctionTemplateDecl.

This fixes #311.

### CODE REVIEW

**Comment by balazske** [comment]
It is possible to remove a part of function `ASTNodeImporter::VisitFunctionDecl` as written in #311 but this is left out now, the fix works without this and with this change too. The change can be done as part of the #300.

**Comment by Xazax-hun** [comment]
https://github.com/Ericsson/clang/pull/300 is now merged. As per our discussion with @szepet , we should not remove the code snippet in question.

File: lib/AST/ASTImporter.cpp [hunk 1]
```diff
@@ -4606,11 +4601,21 @@ Decl *ASTNodeImporter::VisitFunctionTemplateDecl(FunctionTemplateDecl *D) {
     }
   }
```
Comment (gerazo) [inline lib/AST/ASTImporter.cpp]: The code from upper here was moved below this point. Is it because the previous code should not search in the TO context after putting something into it?

File: lib/AST/ASTImporter.cpp [hunk 2]
```diff
@@ -4664,6 +4664,11 @@ Decl *ASTNodeImporter::VisitFunctionTemplateDecl(FunctionTemplateDecl *D) {
   if (!TemplatedFD)
     return nullptr;
 
+  // Check recursive import.
+  Decl *AlreadyImported = Importer.GetAlreadyImportedOrNull(D);
```
Comment (Xazax-hun) [inline lib/AST/ASTImporter.cpp]: I am wondering what should we do with this piece of code right now.
When we are importing the templated FunctionDecl above we will call import on the described template. This will result in a second call to importing the function template where the above import call will return the already imported function decl. After that we finish importing the template. After we imported the function decl and return from the function above we try to finish importing the same function template decl the second time. While having this check is definitely solving the problem I am wondering if there is a nicer solution for this cases in general. While I do agree it is good to fix this problem for now, maybe it worth a fixme to note that this is something that might have a better solution some day. @szepet  what do you think?

**Review by Xazax-hun — COMMENTED** [review]
Overall looks good, but I think this might be a quick fix not the proper solution. Maybe it would be great to add a FIXME. Also, don't we need test for this?

**Comment by Xazax-hun** [comment]
Hmm, I am still thinking if this version or the previous one is the better. I wonder what is the opinion of the others? 
I lean towards the previous one with a FIXME comment. Because in the future if someone rewrites the Importer with a new architecture (e.g. more context available during importing nodes), one could introduce a cleaner solution.

My intuition: the current solution will create nicer call stacks, but might result in more lookups. The previous one is a smaller modification that might be easier to understand, but the call stack and the importing logic is more convoluted that way.

**Comment by balazske** [comment]
There are still some problems with the import: When importing the "templated" function lookup of already imported is not working correctly (somewhat like in the #312 case). This causes additional complexity with the new solution. Maybe the previous version of import is the better one, and import of `RecordDecl` and `ClassTemplateDecl` is done in similar way.

**Comment by Xazax-hun** [comment]
I see, in this case, I am in favor of the previous solution. It looks like this is already a pattern in the importer, let's not break it for now.

File: lib/AST/ASTImporter.cpp [hunk 3]
```diff
@@ -4659,19 +4673,20 @@ Decl *ASTNodeImporter::VisitFunctionTemplateDecl(FunctionTemplateDecl *D) {
   if (!Params)
     return nullptr;
 
-  FunctionDecl *TemplatedFD =
-      cast_or_null<FunctionDecl>(Importer.Import(D->getTemplatedDecl()));
-  if (!TemplatedFD)
-    return nullptr;
+  // Check recursive import.
```
[the remark this answers is not in the document]
Comment (balazske) [reply lib/AST/ASTImporter.cpp]: This is the second solution that tries to avoid the "loop" at template import. Always import the "templated function" first. If the import is called from the templated function (this is indicated by the condition that `TemplatedFD` is non-null) import really the template. If the import is called not from the templated function (`TemplatedFD` should be null) import the templated function, this causes a recursive call with the previous condition, template is imported, and this call returns the already imported template.

But currently the first solution is the likely one.

**Comment by balazske** [comment]
Changes are updated, this should be the final version. (Not the most nice solution but should work.)

**Review by martong — APPROVED** [review]
LGTM! Nice work! Perhaps it can close #319 as well.

**Comment by balazske** [comment]
`clang check-all` passes with this code

**Comment by balazske** [comment]
Upstream revision: https://reviews.llvm.org/D49235
(Not fully related change, other related things are fixed and change in #394 is taken into account.)

**Comment by balazske** [comment]
Backport from upstream: #439
