### PR TITLE
Get the almost upstream version of importing TypeTraitExpr.

### LINKED ISSUE #214: ASTImporter crashes on TypeTraitExpr
```
ANALYZE (CTU loaded AST for source file): ./report_debug/ctu-dir/i386/ast/home/egbomrt/WORK/DebugCrashes/CodeChecker_log/reports/bn_drivers__2017_11_16__15_34_00/failed/hwmon-data_source.cc_bb926846cf0e72792bdadbe888fbcf9f/sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/src/platform/eqm/hwmon-lib/src/hwmon-slot_info.cc
clang-5.0: ../../git/llvm/tools/clang/include/clang/AST/ExprCXX.h:2296: bool clang::TypeTraitExpr::getValue() const: Assertion `!isValueDependent()' failed.
#0 0x00007fa6d26d70b9 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/lib/Support/Unix/Signals.inc:398:11
#1 0x00007fa6d26d7269 PrintStackTraceSignalHandler(void*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/lib/Support/Unix/Signals.inc:462:1
#2 0x00007fa6d26d58c3 llvm::sys::RunSignalHandlers() /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/lib/Support/Signals.cpp:0:5
#3 0x00007fa6d26d75c4 SignalHandler(int) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/lib/Support/Unix/Signals.inc:252:1
#4 0x00007fa6d1946390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#5 0x00007fa6ced59428 gsignal /build/glibc-bfm8X4/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
#6 0x00007fa6ced5b02a abort /build/glibc-bfm8X4/glibc-2.23/stdlib/abort.c:91:0
#7 0x00007fa6ced51bd7 __assert_fail_base /build/glibc-bfm8X4/glibc-2.23/assert/assert.c:92:0
#8 0x00007fa6ced51c82 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc82)
#9 0x00007fa6cb480deb clang::TypeTraitExpr::getValue() const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/AST/ExprCXX.h:2297:30
#10 0x00007fa6cb46eed3 clang::ASTNodeImporter::VisitTypeTraitExpr(clang::TypeTraitExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5275:10
#11 0x00007fa6cb48878b clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:803:1
#12 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#13 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#14 0x00007fa6cb46efc9 clang::ASTNodeImporter::VisitBinaryOperator(clang::BinaryOperator*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5286:9
#15 0x00007fa6cb49d088 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::VisitBinLAnd(clang::BinaryOperator*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/AST/StmtVisitor.h:131:3
#16 0x00007fa6cb48769f clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/AST/StmtVisitor.h:67:26
#17 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#18 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#19 0x00007fa6cb46efc9 clang::ASTNodeImporter::VisitBinaryOperator(clang::BinaryOperator*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5286:9
#20 0x00007fa6cb49d088 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::VisitBinLAnd(clang::BinaryOperator*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/AST/StmtVisitor.h:131:3
#21 0x00007fa6cb48769f clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/AST/StmtVisitor.h:67:26
#22 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#23 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#24 0x00007fa6cb46efc9 clang::ASTNodeImporter::VisitBinaryOperator(clang::BinaryOperator*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5286:9
#25 0x00007fa6cb49d088 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::VisitBinLAnd(clang::BinaryOperator*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/AST/StmtVisitor.h:131:3
#26 0x00007fa6cb48769f clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/include/clang/AST/StmtVisitor.h:67:26
#27 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#28 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#29 0x00007fa6cb46e2a7 clang::ASTNodeImporter::VisitParenExpr(clang::ParenExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:5182:9
#30 0x00007fa6cb488673 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:743:1
#31 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#32 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#33 0x00007fa6cb4535a6 clang::ASTNodeImporter::ImportDefinition(clang::VarDecl*, clang::VarDecl*, clang::ASTNodeImporter::ImportDefinitionKind) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1148:7
#34 0x00007fa6cb45ee9c clang::ASTNodeImporter::VisitVarDecl(clang::VarDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2762:7
#35 0x00007fa6cb48695c clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:441:1
#36 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#37 0x00007fa6cb477940 clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0::operator()(clang::Decl*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4397:7
#38 0x00007fa6cb468d76 clang::Decl** std::transform<clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0>(clang::Decl**, clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#39 0x00007fa6cb468ce4 clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4399:31
#40 0x00007fa6cb46961b clang::ASTNodeImporter::VisitDeclStmt(clang::DeclStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4486:23
#41 0x00007fa6cb487ba2 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:103:1
#42 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#43 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#44 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#45 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#46 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#47 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#48 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#49 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#50 0x00007fa6cb45b6c5 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2330:15
#51 0x00007fa6cb48687c clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:389:1
#52 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#53 0x00007fa6cb468605 clang::ASTNodeImporter::VisitFunctionTemplateDecl(clang::FunctionTemplateDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4333:7
#54 0x00007fa6cb4865f8 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:201:1
#55 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#56 0x00007fa6cb453377 clang::ASTNodeImporter::ImportDeclContext(clang::DeclContext*, bool, clang::DeclContext*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1007:30
#57 0x00007fa6cb455b36 clang::ASTNodeImporter::VisitNamespaceDecl(clang::NamespaceDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1560:10
#58 0x00007fa6cb4864a8 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:105:1
#59 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#60 0x00007fa6cb4515ee clang::ASTImporter::ImportContext(clang::DeclContext*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6458:23
#61 0x00007fa6cb451412 clang::ASTNodeImporter::ImportDeclParts(clang::NamedDecl*, clang::DeclContext*&, clang::DeclContext*&, clang::DeclarationName&, clang::NamedDecl*&, clang::SourceLocation&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:913:3
#62 0x00007fa6cb46856c clang::ASTNodeImporter::VisitFunctionTemplateDecl(clang::FunctionTemplateDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4326:7
#63 0x00007fa6cb4865f8 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:201:1
#64 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#65 0x00007fa6cb474c2a clang::ASTNodeImporter::VisitUnresolvedLookupExpr(clang::UnresolvedLookupExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6061:26
#66 0x00007fa6cb48861f clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:721:1
#67 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#68 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#69 0x00007fa6cb475ca1 clang::ASTNodeImporter::VisitCallExpr(clang::CallExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6176:9
#70 0x00007fa6cb487fab clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:329:1
#71 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#72 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#73 0x00007fa6cb46b190 clang::ASTNodeImporter::VisitReturnStmt(clang::ReturnStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4747:9
#74 0x00007fa6cb488ec3 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:1219:1
#75 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#76 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#77 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#78 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#79 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#80 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#81 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#82 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#83 0x00007fa6cb45b6c5 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2330:15
#84 0x00007fa6cb48687c clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:389:1
#85 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#86 0x00007fa6cb468605 clang::ASTNodeImporter::VisitFunctionTemplateDecl(clang::FunctionTemplateDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4333:7
#87 0x00007fa6cb4865f8 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:201:1
#88 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#89 0x00007fa6cb474c2a clang::ASTNodeImporter::VisitUnresolvedLookupExpr(clang::UnresolvedLookupExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6061:26
#90 0x00007fa6cb48861f clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:721:1
#91 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#92 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#93 0x00007fa6cb475ca1 clang::ASTNodeImporter::VisitCallExpr(clang::CallExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6176:9
#94 0x00007fa6cb49d808 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::VisitCXXOperatorCallExpr(clang::CXXOperatorCallExpr*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:345:1
#95 0x00007fa6cb487fff clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:345:1
#96 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#97 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#98 0x00007fa6cb475d5f clang::ASTNodeImporter::VisitCallExpr(clang::CallExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6186:11
#99 0x00007fa6cb487fab clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:329:1
#100 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#101 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#102 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#103 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#104 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#105 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#106 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#107 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#108 0x00007fa6cb45b6c5 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2330:15
#109 0x00007fa6cb48687c clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:389:1
#110 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#111 0x00007fa6cb468605 clang::ASTNodeImporter::VisitFunctionTemplateDecl(clang::FunctionTemplateDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4333:7
#112 0x00007fa6cb4865f8 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:201:1
#113 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#114 0x00007fa6cb474c2a clang::ASTNodeImporter::VisitUnresolvedLookupExpr(clang::UnresolvedLookupExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6061:26
#115 0x00007fa6cb48861f clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:721:1
#116 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#117 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#118 0x00007fa6cb475ca1 clang::ASTNodeImporter::VisitCallExpr(clang::CallExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6176:9
#119 0x00007fa6cb49d808 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::VisitCXXOperatorCallExpr(clang::CXXOperatorCallExpr*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:345:1
#120 0x00007fa6cb487fff clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:345:1
#121 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#122 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#123 0x00007fa6cb475d5f clang::ASTNodeImporter::VisitCallExpr(clang::CallExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6186:11
#124 0x00007fa6cb487fab clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:329:1
#125 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#126 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#127 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#128 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#129 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#130 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#131 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#132 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#133 0x00007fa6cb45b6c5 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2330:15
#134 0x00007fa6cb48687c clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:389:1
#135 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#136 0x00007fa6cb4515ee clang::ASTImporter::ImportContext(clang::DeclContext*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6458:23
#137 0x00007fa6cb451412 clang::ASTNodeImporter::ImportDeclParts(clang::NamedDecl*, clang::DeclContext*&, clang::DeclContext*&, clang::DeclarationName&, clang::NamedDecl*&, clang::SourceLocation&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:913:3
#138 0x00007fa6cb455fa9 clang::ASTNodeImporter::VisitTypedefNameDecl(clang::TypedefNameDecl*, bool) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1607:7
#139 0x00007fa6cb456a1f clang::ASTNodeImporter::VisitTypedefDecl(clang::TypedefDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1683:3
#140 0x00007fa6cb486748 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:303:1
#141 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#142 0x00007fa6cb477940 clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0::operator()(clang::Decl*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4397:7
#143 0x00007fa6cb468d76 clang::Decl** std::transform<clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0>(clang::Decl**, clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#144 0x00007fa6cb468ce4 clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4399:31
#145 0x00007fa6cb46961b clang::ASTNodeImporter::VisitDeclStmt(clang::DeclStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4486:23
#146 0x00007fa6cb487ba2 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:103:1
#147 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#148 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#149 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#150 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#151 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#152 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#153 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#154 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#155 0x00007fa6cb45b6c5 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2330:15
#156 0x00007fa6cb48687c clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:389:1
#157 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#158 0x00007fa6cb468605 clang::ASTNodeImporter::VisitFunctionTemplateDecl(clang::FunctionTemplateDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4333:7
#159 0x00007fa6cb4865f8 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:201:1
#160 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#161 0x00007fa6cb474c2a clang::ASTNodeImporter::VisitUnresolvedLookupExpr(clang::UnresolvedLookupExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6061:26
#162 0x00007fa6cb48861f clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:721:1
#163 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#164 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#165 0x00007fa6cb475ca1 clang::ASTNodeImporter::VisitCallExpr(clang::CallExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6176:9
#166 0x00007fa6cb49d808 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::VisitCXXOperatorCallExpr(clang::CXXOperatorCallExpr*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:345:1
#167 0x00007fa6cb487fff clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:345:1
#168 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#169 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#170 0x00007fa6cb475d5f clang::ASTNodeImporter::VisitCallExpr(clang::CallExpr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6186:11
#171 0x00007fa6cb487fab clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:329:1
#172 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#173 0x00007fa6cb44e965 clang::ASTImporter::Import(clang::Expr*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6513:10
#174 0x00007fa6cb4535a6 clang::ASTNodeImporter::ImportDefinition(clang::VarDecl*, clang::VarDecl*, clang::ASTNodeImporter::ImportDefinitionKind) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1148:7
#175 0x00007fa6cb45ee9c clang::ASTNodeImporter::VisitVarDecl(clang::VarDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2762:7
#176 0x00007fa6cb48695c clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:441:1
#177 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#178 0x00007fa6cb477940 clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0::operator()(clang::Decl*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4397:7
#179 0x00007fa6cb468d76 clang::Decl** std::transform<clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0>(clang::Decl**, clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#180 0x00007fa6cb468ce4 clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4399:31
#181 0x00007fa6cb46961b clang::ASTNodeImporter::VisitDeclStmt(clang::DeclStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4486:23
#182 0x00007fa6cb487ba2 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:103:1
#183 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#184 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#185 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#186 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#187 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#188 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#189 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#190 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#191 0x00007fa6cb46a2d4 clang::ASTNodeImporter::VisitIfStmt(clang::IfStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4592:9
#192 0x00007fa6cb48884f clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:849:1
#193 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#194 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#195 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#196 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#197 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#198 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#199 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#200 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#201 0x00007fa6cb46a81c clang::ASTNodeImporter::VisitWhileStmt(clang::WhileStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4656:9
#202 0x00007fa6cb488fa3 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:1275:1
#203 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#204 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#205 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#206 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#207 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#208 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#209 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#210 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#211 0x00007fa6cb46b415 clang::ASTNodeImporter::VisitCXXTryStmt(clang::CXXTryStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4777:9
#212 0x00007fa6cb487afa clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:67:1
#213 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#214 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#215 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#216 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#217 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#218 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#219 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#220 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#221 0x00007fa6cb45b6c5 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2330:15
#222 0x00007fa6cb45befd clang::ASTNodeImporter::VisitCXXMethodDecl(clang::CXXMethodDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2347:3
#223 0x00007fa6cb4868b4 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:399:1
#224 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#225 0x00007fa6cb468605 clang::ASTNodeImporter::VisitFunctionTemplateDecl(clang::FunctionTemplateDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4333:7
#226 0x00007fa6cb4865f8 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:201:1
#227 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#228 0x00007fa6cb453377 clang::ASTNodeImporter::ImportDeclContext(clang::DeclContext*, bool, clang::DeclContext*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1007:30
#229 0x00007fa6cb455b36 clang::ASTNodeImporter::VisitNamespaceDecl(clang::NamespaceDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1560:10
#230 0x00007fa6cb4864a8 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:105:1
#231 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#232 0x00007fa6cb4515ee clang::ASTImporter::ImportContext(clang::DeclContext*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6458:23
#233 0x00007fa6cb451412 clang::ASTNodeImporter::ImportDeclParts(clang::NamedDecl*, clang::DeclContext*&, clang::DeclContext*&, clang::DeclarationName&, clang::NamedDecl*&, clang::SourceLocation&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:913:3
#234 0x00007fa6cb459dbc clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:2128:7
#235 0x00007fa6cb48687c clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:389:1
#236 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#237 0x00007fa6cb4515ee clang::ASTImporter::ImportContext(clang::DeclContext*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6458:23
#238 0x00007fa6cb451412 clang::ASTNodeImporter::ImportDeclParts(clang::NamedDecl*, clang::DeclContext*&, clang::DeclContext*&, clang::DeclarationName&, clang::NamedDecl*&, clang::SourceLocation&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:913:3
#239 0x00007fa6cb455fa9 clang::ASTNodeImporter::VisitTypedefNameDecl(clang::TypedefNameDecl*, bool) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1607:7
#240 0x00007fa6cb456a1f clang::ASTNodeImporter::VisitTypedefDecl(clang::TypedefDecl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:1683:3
#241 0x00007fa6cb486748 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::ASTNodeImporter, clang::Decl*>::Visit(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/DeclNodes.inc:303:1
#242 0x00007fa6cb44f26a clang::ASTImporter::Import(clang::Decl*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6422:9
#243 0x00007fa6cb477940 clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0::operator()(clang::Decl*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4397:7
#244 0x00007fa6cb468d76 clang::Decl** std::transform<clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0>(clang::Decl**, clang::Decl**, clang::Decl**, clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef)::$_0) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#245 0x00007fa6cb468ce4 clang::ASTNodeImporter::ImportDeclGroup(clang::DeclGroupRef) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4399:31
#246 0x00007fa6cb46961b clang::ASTNodeImporter::VisitDeclStmt(clang::DeclStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4486:23
#247 0x00007fa6cb487ba2 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:103:1
#248 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
#249 0x00007fa6cb497057 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}::operator()(clang::Stmt*) const /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:325:36
#250 0x00007fa6cb496ffa clang::Stmt** std::transform<clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}>(clang::Stmt**, clang::Stmt**, clang::Stmt**, bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**)::{lambda(clang::Stmt*)#1}) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:4306:3
#251 0x00007fa6cb496f60 bool clang::ASTNodeImporter::ImportArrayChecked<clang::Stmt**, clang::Stmt**>(clang::Stmt**, clang::Stmt**, clang::Stmt**) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:331:14
#252 0x00007fa6cb47d8ac bool clang::ASTNodeImporter::ImportContainerChecked<llvm::iterator_range<clang::Stmt**>, llvm::SmallVector<clang::Stmt*, 8u> >(llvm::iterator_range<clang::Stmt**> const&, llvm::SmallVector<clang::Stmt*, 8u>&) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:337:7
#253 0x00007fa6cb46986c clang::ASTNodeImporter::VisitCompoundStmt(clang::CompoundStmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:4505:7
#254 0x00007fa6cb487b32 clang::StmtVisitorBase<clang::make_ptr, clang::ASTNodeImporter, clang::Stmt*>::Visit(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/tools/clang/include/clang/AST/StmtNodes.inc:79:1
#255 0x00007fa6cb457593 clang::ASTImporter::Import(clang::Stmt*) /home/egbomrt/WORK/llvm/build/debug/../../git/llvm/tools/clang/lib/AST/ASTImporter.cpp:6527:9
Stack dump:
0.	Program arguments: /home/egbomrt/WORK/llvm/build/debug/bin/clang-5.0 -cc1 -triple powerpc-montavista-linux-gnu -analyze -disable-free -main-file-name hwmon-data_source.cc -analyzer-store=region -analyzer-opt-analyze-nested-blocks -analyzer-eagerly-assume -analyzer-output plist -w -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -target-cpu ppc -mfloat-abi hard -momit-leaf-frame-pointer -dwarf-column-info -debugger-tuning=gdb -resource-dir ./sources-root/proj/tn/tools/code_checker/CodeChecker_6.2.0/include -isystem ./sources-root/proj/tn/tools/code_checker/CodeChecker_6.2.0/include -isystem ./sources-root/proj/tn/build/toolchain/e5500/R1A03/montavista/tools/powerpc64-gnu/powerpc64-montavista-linux-gnu/include/c++/4.7.0 -isystem ./sources-root/proj/tn/build/toolchain/e5500/R1A03/montavista/tools/powerpc64-gnu/powerpc64-montavista-linux-gnu/include/c++/4.7.0/powerpc64-montavista-linux-gnu/32 -isystem ./sources-root/proj/tn/build/toolchain/e5500/R1A03/montavista/tools/powerpc64-gnu/powerpc64-montavista-linux-gnu/include/c++/4.7.0/backward -isystem ./sources-root/proj/tn/build/toolchain/e5500/R1A03/montavista/tools/powerpc64-gnu/lib/gcc/powerpc64-montavista-linux-gnu/4.7.0/include -isystem ./sources-root/proj/tn/build/toolchain/e5500/R1A03/montavista/tools/powerpc64-gnu/lib/gcc/powerpc64-montavista-linux-gnu/4.7.0/include-fixed -isystem ./sources-root/proj/tn/build/toolchain/e5500/R1A03/montavista/tools/powerpc64-gnu/powerpc64-montavista-linux-gnu/include -isystem ./sources-root/proj/tn/build/sysroot/e5500/R1A04/usr/include -D ARCH_e5500 -D BNS_APP_SECURITY_FEATURE -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/envoy/target/h -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/xf -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/cmo -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/smo -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/tm -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/lch -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/tnu -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/rph -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/radius -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/rauth -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/include/eqm -I ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/src/platform/eqm/hwmon-lib/include -D RELEASE -isysroot ./sources-root/proj/tn/build/sysroot/e5500/R1A04 -internal-isystem ./sources-root/proj/tn/build/sysroot/e5500/R1A04/usr/local/include -internal-isystem ./sources-root/proj/tn/tools/code_checker/CodeChecker_6.2.0/include/include -internal-externc-isystem ./sources-root/proj/tn/build/sysroot/e5500/R1A04/include -internal-externc-isystem ./sources-root/proj/tn/build/sysroot/e5500/R1A04/usr/include -O2 -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /home/egbomrt/WORK/DebugCrashes/CodeChecker_log/reports/bn_drivers__2017_11_16__15_34_00/failed/hwmon-data_source.cc_bb926846cf0e72792bdadbe888fbcf9f -ferror-limit 19 -fmessage-length 0 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-loops -vectorize-slp -plugin checkercfg -load /home/egbomrt/WORK/codechecker_core_ws/build/debug/libericsson-checkers.so -analyzer-opt-analyze-headers -analyzer-output=plist-multi-file -analyzer-disable-checker alpha.clone.CloneChecker -analyzer-disable-checker alpha.core.BoolAssignment -analyzer-disable-checker alpha.core.CallAndMessageUnInitRefArg -analyzer-disable-checker alpha.core.CastSize -analyzer-disable-checker alpha.core.CastToStruct -analyzer-disable-checker alpha.core.Conversion -analyzer-disable-checker alpha.core.DynamicTypeChecker -analyzer-disable-checker alpha.core.FixedAddr -analyzer-disable-checker alpha.core.IdenticalExpr -analyzer-disable-checker alpha.core.PointerArithm -analyzer-disable-checker alpha.core.PointerSub -analyzer-disable-checker alpha.core.SizeofPtr -analyzer-disable-checker alpha.core.TestAfterDivZero -analyzer-disable-checker alpha.cplusplus.IteratorRange -analyzer-disable-checker alpha.cplusplus.MisusedMovedObject -analyzer-disable-checker alpha.deadcode.UnreachableCode -analyzer-disable-checker alpha.ericsson.cpp.BitwiseShift -analyzer-disable-checker alpha.ericsson.cpp.CtorUninitializedMember -analyzer-disable-checker alpha.ericsson.cpp.DirtyScalar -analyzer-disable-checker alpha.ericsson.cpp.ExceptionMisuse -analyzer-disable-checker alpha.ericsson.cpp.InvariablePtrBranch -analyzer-disable-checker alpha.ericsson.cpp.IteratorOutOfRange -analyzer-disable-checker alpha.ericsson.cpp.MismatchedIterator -analyzer-disable-checker alpha.ericsson.cpp.MissingHeaderGuard -analyzer-disable-checker alpha.ericsson.cpp.OStreamFormat -analyzer-disable-checker alpha.ericsson.cpp.PointerArithmetic -analyzer-disable-checker alpha.ericsson.cpp.Slicing -analyzer-disable-checker alpha.ericsson.cpp.stl.MissingIteratorAdapter -analyzer-disable-checker alpha.ericsson.cpp.style.PreferInit -analyzer-disable-checker alpha.ericsson.statisticsbased.SpecialReturnValue -analyzer-disable-checker alpha.ericsson.statisticsbased.UncheckedReturnValue -analyzer-disable-checker alpha.ericsson.statisticscollector.ReturnValueCheck -analyzer-disable-checker alpha.ericsson.statisticscollector.SpecialReturnValue -analyzer-disable-checker alpha.osx.cocoa.DirectIvarAssignment -analyzer-disable-checker alpha.osx.cocoa.DirectIvarAssignmentForAnnotatedFunctions -analyzer-disable-checker alpha.osx.cocoa.InstanceVariableInvalidation -analyzer-disable-checker alpha.osx.cocoa.MissingInvalidationMethod -analyzer-disable-checker alpha.osx.cocoa.localizability.PluralMisuseChecker -analyzer-disable-checker alpha.security.ArrayBound -analyzer-disable-checker alpha.security.ArrayBoundV2 -analyzer-disable-checker alpha.security.MallocOverflow -analyzer-disable-checker alpha.security.ReturnPtrRange -analyzer-disable-checker alpha.security.taint.TaintPropagation -analyzer-disable-checker alpha.unix.BlockInCriticalSection -analyzer-disable-checker alpha.unix.Chroot -analyzer-disable-checker alpha.unix.PthreadLock -analyzer-disable-checker alpha.unix.SimpleStream -analyzer-disable-checker alpha.unix.Stream -analyzer-disable-checker alpha.unix.cstring.BufferOverlap -analyzer-disable-checker alpha.unix.cstring.NotNullTerminated -analyzer-disable-checker alpha.unix.cstring.OutOfBounds -analyzer-checker=apiModeling.google.GTest -analyzer-checker=core.CallAndMessage -analyzer-checker=core.DivideZero -analyzer-checker=core.DynamicTypePropagation -analyzer-checker=core.NonNullParamChecker -analyzer-checker=core.NullDereference -analyzer-checker=core.StackAddressEscape -analyzer-checker=core.UndefinedBinaryOperatorResult -analyzer-checker=core.VLASize -analyzer-checker=core.builtin.BuiltinFunctions -analyzer-checker=core.builtin.NoReturnFunctions -analyzer-checker=core.uninitialized.ArraySubscript -analyzer-checker=core.uninitialized.Assign -analyzer-checker=core.uninitialized.Branch -analyzer-checker=core.uninitialized.CapturedBlockVariable -analyzer-checker=core.uninitialized.UndefReturn -analyzer-checker=cplusplus.NewDelete -analyzer-checker=cplusplus.NewDeleteLeaks -analyzer-checker=cplusplus.SelfAssignment -analyzer-checker=deadcode.DeadStores -analyzer-disable-checker debug.AnalysisOrder -analyzer-disable-checker debug.ConfigDumper -analyzer-disable-checker debug.DumpCFG -analyzer-disable-checker debug.DumpCallGraph -analyzer-disable-checker debug.DumpCalls -analyzer-disable-checker debug.DumpDominators -analyzer-disable-checker debug.DumpLiveVars -analyzer-disable-checker debug.DumpTraversal -analyzer-disable-checker debug.ExprInspection -analyzer-disable-checker debug.Stats -analyzer-disable-checker debug.TaintTest -analyzer-disable-checker debug.ViewCFG -analyzer-disable-checker debug.ViewCallGraph -analyzer-disable-checker debug.ViewExplodedGraph -analyzer-disable-checker ericsson.cpp.InvalidatedIterator -analyzer-checker=ericsson.cpp.MisuseEnumAsCondition -analyzer-checker=ericsson.cpp.PredWithState -analyzer-checker=ericsson.cpp.RaiiMisuse -analyzer-checker=ericsson.cpp.StrlenMisuseAlloc -analyzer-checker=ericsson.cpp.SuspiciousPointerArithmetic -analyzer-checker=ericsson.cpp.SuspiciousSizeof -analyzer-checker=ericsson.cpp.VirtualDtorPoly -analyzer-checker=ericsson.cpp.stl.ContainerOfAutoptr -analyzer-checker=ericsson.cpp.stl.MisusedRemove -analyzer-checker=ericsson.cpp.stl.PolymorphContainer -analyzer-checker=ericsson.cpp.stl.RevIterBase -analyzer-checker=ericsson.cpp.style.CatchByValue -analyzer-disable-checker ericsson.cpp.style.Goto -analyzer-checker=ericsson.cpp.style.LargeObjectPassed -analyzer-disable-checker ericsson.cpp.style.MagicNumbers -analyzer-disable-checker ericsson.cpp.style.MissingConst -analyzer-disable-checker ericsson.cpp.style.New -analyzer-disable-checker ericsson.cpp.style.NonPrivateData -analyzer-disable-checker ericsson.cpp.style.ReduceScope -analyzer-disable-checker ericsson.cpp.style.ReinterpretCast -analyzer-disable-checker ericsson.linuxkernelstyle.PointerDecl -analyzer-disable-checker ericsson.misrac.AssignmentInCondition -analyzer-disable-checker ericsson.misrac.ExternalArrayWithUnknownSize -analyzer-disable-checker ericsson.misrac.FunctionsWithNoParam -analyzer-disable-checker ericsson.misrac.IfFollowedByCompound -analyzer-disable-checker ericsson.misrac.SwitchDefaultBranch -analyzer-disable-checker ericsson.mtas.DbnDelayAfterRetry -analyzer-disable-checker ericsson.mtas.DialogueSetupCreate -analyzer-disable-checker ericsson.mtas.EpctParameters -analyzer-disable-checker ericsson.mtas.IllegalTracing -analyzer-disable-checker ericsson.mtas.LicenseManagement -analyzer-disable-checker ericsson.mtas.MtasConventions -analyzer-disable-checker ericsson.mtas.SerializeVersion -analyzer-disable-checker ericsson.mtas.SerializeWithoutObserver -analyzer-checker=ericsson.precpp11.stl.AllocWithState -analyzer-checker=ericsson.precpp11.stl.BinFunctorTypeMismatch -analyzer-checker=ericsson.precpp11.stl.UnaryFunctorTypeMismatch -analyzer-disable-checker ericsson.tsp.DbnTransactionManagement -analyzer-disable-checker ericsson.tsp.PointerCompare -analyzer-disable-checker ericsson.tsp.TspBuiltinTypes -analyzer-disable-checker ericsson.utility.WarningToReportConverter -analyzer-disable-checker llvm.Conventions -analyzer-checker=nullability.NullPassedToNonnull -analyzer-checker=nullability.NullReturnedFromNonnull -analyzer-disable-checker nullability.NullableDereferenced -analyzer-disable-checker nullability.NullablePassedToNonnull -analyzer-disable-checker nullability.NullableReturnedFromNonnull -analyzer-disable-checker optin.cplusplus.VirtualCall -analyzer-disable-checker optin.mpi.MPI-Checker -analyzer-disable-checker optin.osx.cocoa.localizability.EmptyLocalizationContextChecker -analyzer-disable-checker optin.osx.cocoa.localizability.NonLocalizedStringChecker -analyzer-disable-checker optin.performance.Padding -analyzer-disable-checker optin.portability.UnixAPI -analyzer-disable-checker osx.API -analyzer-disable-checker osx.NumberObjectConversion -analyzer-disable-checker osx.ObjCProperty -analyzer-disable-checker osx.SecKeychainAPI -analyzer-disable-checker osx.cocoa.AtSync -analyzer-disable-checker osx.cocoa.ClassRelease -analyzer-disable-checker osx.cocoa.Dealloc -analyzer-disable-checker osx.cocoa.IncompatibleMethodTypes -analyzer-disable-checker osx.cocoa.Loops -analyzer-disable-checker osx.cocoa.MissingSuperCall -analyzer-disable-checker osx.cocoa.NSAutoreleasePool -analyzer-disable-checker osx.cocoa.NSError -analyzer-disable-checker osx.cocoa.NilArg -analyzer-disable-checker osx.cocoa.NonNilReturnValue -analyzer-disable-checker osx.cocoa.ObjCGenerics -analyzer-disable-checker osx.cocoa.RetainCount -analyzer-disable-checker osx.cocoa.SelfInit -analyzer-disable-checker osx.cocoa.SuperDealloc -analyzer-disable-checker osx.cocoa.UnusedIvars -analyzer-disable-checker osx.cocoa.VariadicMethodTypes -analyzer-disable-checker osx.coreFoundation.CFError -analyzer-disable-checker osx.coreFoundation.CFNumber -analyzer-disable-checker osx.coreFoundation.CFRetainRelease -analyzer-disable-checker osx.coreFoundation.containers.OutOfBounds -analyzer-disable-checker osx.coreFoundation.containers.PointerSizedValues -analyzer-checker=security.FloatLoopCounter -analyzer-checker=security.insecureAPI.UncheckedReturn -analyzer-checker=security.insecureAPI.getpw -analyzer-checker=security.insecureAPI.gets -analyzer-checker=security.insecureAPI.mkstemp -analyzer-checker=security.insecureAPI.mktemp -analyzer-checker=security.insecureAPI.rand -analyzer-disable-checker security.insecureAPI.strcpy -analyzer-checker=security.insecureAPI.vfork -analyzer-checker=unix.API -analyzer-checker=unix.Malloc -analyzer-checker=unix.MallocSizeof -analyzer-checker=unix.MismatchedDeallocator -analyzer-checker=unix.StdCLibraryFunctions -analyzer-checker=unix.Vfork -analyzer-checker=unix.cstring.BadSizeArg -analyzer-checker=unix.cstring.NullArg -analyzer-checker=valist.CopyToSelf -analyzer-checker=valist.Uninitialized -analyzer-checker=valist.Unterminated -analyzer-config xtu-dir=./report_debug/ctu-dir/i386 -analyzer-display-ctu-progress -o ./sources-root/local/scratch/repos/ML66/reports/bn_drivers__2017_11_16__15_34_00/hwmon-data_source.cc_bb926846cf0e72792bdadbe888fbcf9f.plist -x c++ ./sources-root/local/scratch/repos/ML66/ml66_nps/submodules/ml66_common/src/platform/eqm/hwmon-lib/src/hwmon-data_source.cc 
1.	<eof> parser at end of file
2.	While analyzing stack: 
	#0 template<> inline void _Construct<SlotInfo, <const SlotInfo &>>(SlotInfo *__p, const SlotInfo &&__args)
	#1 template<> static SlotInfo *__uninit_copy<__gnu_cxx::__normal_iterator<const SlotInfo *, std::vector<SlotInfo, std::allocator<SlotInfo> > >, SlotInfo *>(__gnu_cxx::__normal_iterator<const SlotInfo *, std::vector<SlotInfo, std::allocator<SlotInfo> > > __first, __gnu_cxx::__normal_iterator<const SlotInfo *, std::vector<SlotInfo, std::allocator<SlotInfo> > > __last, SlotInfo *__result)
	#2 template<> inline SlotInfo *uninitialized_copy<__gnu_cxx::__normal_iterator<const SlotInfo *, std::vector<SlotInfo, std::allocator<SlotInfo> > >, SlotInfo *>(__gnu_cxx::__normal_iterator<const SlotInfo *, std::vector<SlotInfo, std::allocator<SlotInfo> > > __first, __gnu_cxx::__normal_iterator<const SlotInfo *, std::vector<SlotInfo, std::allocator<SlotInfo> > > __last, SlotInfo *__result)
	#3 template<> inline SlotInfo *__uninitialized_copy_a<__gnu_cxx::__normal_iterator<const SlotInfo *, std::vector<SlotInfo, std::allocator<SlotInfo> > >, SlotInfo *, SlotInfo>(__gnu_cxx::__normal_iterator<const SlotInfo *, std::vector<SlotInfo, std::allocator<SlotInfo> > > __first, __gnu_cxx::__normal_iterator<const SlotInfo *, std::vector<SlotInfo, std::allocator<SlotInfo> > > __last, SlotInfo *__result, allocator<SlotInfo> &)
	#4 vector(const std::vector<SlotInfo, std::allocator<SlotInfo> > &__x) : std::vector<SlotInfo, std::allocator<SlotInfo> >::_Base(__x.size(), _Alloc_traits::_S_select_on_copy(__x._M_get_Tp_allocator())) {}
3.	./sources-root/proj/tn/build/toolchain/e5500/R1A03/montavista/tools/powerpc64-gnu/powerpc64-montavista-linux-gnu/include/c++/4.7.0/bits/stl_construct.h:77:38: Error evaluating statement
4.	./sources-root/proj/tn/build/toolchain/e5500/R1A03/montavista/tools/powerpc64-gnu/powerpc64-montavista-linux-gnu/include/c++/4.7.0/bits/stl_construct.h:77:38: Error evaluating statement
clang-5.0: error: unable to execute command: Aborted (core dumped)
clang-5.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 5.0.0 (git@github.com:martong/clang.git cfdfecd3398c2645b04a1b44d25636ee82cae56a) (git@github.com:llvm-mirror/llvm.git 657c31173ea30090583e40c7a9204561d9c2d8c4)
Target: powerpc-montavista-linux-gnu
Thread model: posix
InstalledDir: /home/egbomrt/WORK/llvm/build/debug/bin
clang-5.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-5.0: error: unable to execute command: Aborted (core dumped)
clang-5.0: note: diagnostic msg: Error generating preprocessed source(s).
```

### PR DESCRIPTION
**Pull request by Xazax-hun**
Fixes #214.

### CODE REVIEW

File: lib/AST/ASTImporter.cpp [hunk 1]
```diff
@@ -304,7 +304,6 @@ namespace clang {
     Expr *VisitCXXNamedCastExpr(CXXNamedCastExpr *E);
     Expr *VisitSubstNonTypeTemplateParmExpr(SubstNonTypeTemplateParmExpr *E);
 
-
```
Comment (szepet) [inline lib/AST/ASTImporter.cpp]: unnecessary line remove

File: lib/AST/ASTImporter.cpp [hunk 2]
```diff
@@ -6334,6 +6308,26 @@ Expr *ASTNodeImporter::VisitSubstNonTypeTemplateParmExpr(
         Replacement);
 }
 
+Expr *ASTNodeImporter::VisitTypeTraitExpr(TypeTraitExpr *E) {
```
Comment (szepet) [inline lib/AST/ASTImporter.cpp]: why the function has to be moved?
If this version is going to be upstreamed and you think it is better to move it as well, then I am fine with that. Just see no reason for the line change.

File: lib/AST/ASTImporter.cpp (hunk 1 above)
Comment (Xazax-hun) [reply lib/AST/ASTImporter.cpp]: Done.
