### PR TITLE
Fix handling of friend class with unelaborated type

### LINKED ISSUE #560: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
E/// wrat.

### PR DESCRIPTION
**Pull request by martong**
Fixes #560

### CODE REVIEW

**Review by balazske — APPROVED** [review]

File: lib/AST/ASTImporterLookupTable.cpp [hunk 1]
```diff
@@ -30,13 +30,13 @@ struct Builder : RecursiveASTVisitor<Builder> {
   bool VisitFriendDecl(FriendDecl *D) {
     if (D->getFriendType()) {
       QualType Ty = D->getFriendType()->getType();
-      // FIXME Can this be other than elaborated?
-      QualType NamedTy = cast<ElaboratedType>(Ty)->getNamedType();
-      if (!NamedTy->isDependentType()) {
-        if (const auto *RTy = dyn_cast<RecordType>(NamedTy))
+      if (isa<ElaboratedType>(Ty))
```
Comment (balazske) [inline lib/AST/ASTImporterLookupTable.cpp:33]: Are here no other cases possible?

Comment (martong) [reply lib/AST/ASTImporterLookupTable.cpp:33]: I don't know. There may be. So I am going to add an "llvm_unreachable" before commit.
