### PR TITLE
Merge FieldDecl instantiations in ClassTemplateSpecializationDecl

### LINKED ISSUE #440: Radiosw: `Field->getInClassInitializer() && "initializer hasn't been parsed"' failed.
```
#0  0x00007fffedf52428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fffedf5402a in __GI_abort () at abort.c:89
#2  0x00007fffedf4abd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7fffe39bb9bd "Field->getInClassInitializer() && \"initializer hasn't been parsed\"", file=file@entry=0x7fffe399cf86 "../../git/llvm/tools/clang/include/clang/AST/ExprCXX.h", line=line@entry=1142, function=function@entry=0x7fffe39bba00 "const clang::Expr *clang::CXXDefaultInitExpr::getExpr() const") at assert.c:92
#3  0x00007fffedf4ac82 in __GI___assert_fail (assertion=0x7fffe39bb9bd "Field->getInClassInitializer() && \"initializer hasn't been parsed\"", file=0x7fffe399cf86 "../../git/llvm/tools/clang/include/clang/AST/ExprCXX.h", line=1142, function=0x7fffe39bba00 "const clang::Expr *clang::CXXDefaultInitExpr::getExpr() const") at assert.c:101
#4  0x00007fffe386865e in clang::CXXDefaultInitExpr::getExpr (this=0x5002228) at ../../git/llvm/tools/clang/include/clang/AST/ExprCXX.h:1142
#5  0x00007fffe385a870 in clang::ento::ExprEngine::Visit (this=0x7fffffff1050, S=0x5002228, Pred=0x53b8558, DstTop=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:1125
#6  0x00007fffe3858641 in clang::ento::ExprEngine::ProcessStmt (this=0x7fffffff1050, S=..., Pred=0x53b83e0) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:566
#7  0x00007fffe38582fa in clang::ento::ExprEngine::processCFGElement (this=0x7fffffff1050, E=..., Pred=0x53b83e0, StmtIdx=5, Ctx=0x7fffffff0b38) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:410
#8  0x00007fffe383bb06 in clang::ento::CoreEngine::HandlePostStmt (this=0x7fffffff1070, B=0x539a0e8, StmtIdx=5, Pred=0x53b83e0) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:531
#9  0x00007fffe383b406 in clang::ento::CoreEngine::dispatchWorkItem (this=0x7fffffff1070, Pred=0x53b83e0, Loc=..., WU=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:279
#10 0x00007fffe383af68 in clang::ento::CoreEngine::ExecuteWorkList (this=0x7fffffff1070, L=0x37c43a0, Steps=224903, InitState=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp:235
#11 0x00007fffe5554925 in clang::ento::ExprEngine::ExecuteWorkList (this=0x7fffffff1050, L=0x37c43a0, Steps=225000) at ../../git/llvm/tools/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h:114
#12 0x00007fffe54f51eb in (anonymous namespace)::AnalysisConsumer::ActionExprEngine (this=0x6b5c80, D=0x29dafd8, ObjCGCEnabled=false, IMode=clang::ento::ExprEngine::Inline_Regular, VisitedCallees=0x7fffffff1708) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:720
#13 0x00007fffe54f4f81 in (anonymous namespace)::AnalysisConsumer::RunPathSensitiveChecks (this=0x6b5c80, D=0x29dafd8, IMode=clang::ento::ExprEngine::Inline_Regular, Visited=0x7fffffff1708) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:741
#14 0x00007fffe54f4c35 in (anonymous namespace)::AnalysisConsumer::HandleCode (this=0x6b5c80, D=0x29dafd8, Mode=2, IMode=clang::ento::ExprEngine::Inline_Regular, VisitedCallees=0x7fffffff1708) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:687
#15 0x00007fffe54e823e in (anonymous namespace)::AnalysisConsumer::HandleDeclsCallGraph (this=0x6b5c80, LocalTUDeclsSize=2599) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:500
#16 0x00007fffe54e64ad in (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit (this=0x6b5c80, C=...) at ../../git/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:552
#17 0x00007fffef09f91e in clang::MultiplexConsumer::HandleTranslationUnit (this=0x6a0a80, Ctx=...) at ../../git/llvm/tools/clang/lib/Frontend/MultiplexConsumer.cpp:311
#18 0x00007fffe8706de6 in clang::ParseAST (S=..., PrintStats=false, SkipFunctionBodies=false) at ../../git/llvm/tools/clang/lib/Parse/ParseAST.cpp:159
#19 0x00007fffef06829c in clang::ASTFrontendAction::ExecuteAction (this=0x694248) at ../../git/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:998
#20 0x00007fffef067d10 in clang::FrontendAction::Execute (this=0x694248) at ../../git/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:897
#21 0x00007fffeefdcf1a in clang::CompilerInstance::ExecuteAction (this=0x670be0, Act=warning: RTTI symbol not found for class '(anonymous namespace)::ParseArgsAction'
...) at ../../git/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:991
#22 0x00007fffeeba3ce6 in clang::ExecuteCompilerInvocation (Clang=0x670be0) at ../../git/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:252
#23 0x0000000000425649 in cc1_main (Argv=llvm::ArrayRef of length 712 = {...}, Argv0=0x7fffffff6238 "/home/egbomrt/WORK/llvm2/build/debug/bin/clang-6.0", MainAddr=0x415d70 <GetExecutablePath[abi:cxx11](char const*, bool)>) at ../../git/llvm/tools/clang/tools/driver/cc1_main.cpp:221
#24 0x0000000000418189 in ExecuteCC1Tool (argv=llvm::ArrayRef of length 714 = {...}, Tool="") at ../../git/llvm/tools/clang/tools/driver/driver.cpp:309
```

### PR DESCRIPTION
**Pull request by martong**
Fixes #440

### CODE REVIEW

File: lib/AST/ASTImporter.cpp [hunk 1]
```diff
@@ -4575,14 +4589,36 @@ Decl *ASTNodeImporter::VisitClassTemplateSpecializationDecl(
...
     }
+
+    if (IsStructuralMatch(D, FoundDef)) {
+
+      Importer.MapImported(D, FoundDef);
+
+      // Check and merge those fields which have been instantiated
+      // in the "From" context, but not in the "To" context.
+      for (auto *FromField : D->fields()) {
+        Importer.Import(FromField);
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp:4608]: There can be some check for nullptr result of the import, at least a warning (but return nullptr is not possible here).

Comment (martong) [reply lib/AST/ASTImporter.cpp:4608]: It is not exactly clear for me, what could we benefit from a warning?
Either the field is already in the "To" context, then `Import` will not return a nullptr, or it is getting imported newly and that import may fail with a nullptr.
Perhaps we should think about to report an ODR violation if there is a new Field instead.

Comment (balazske) [reply lib/AST/ASTImporter.cpp:4608]: If a field was not imported correctly it can cause errors later at analyze, a warning can give help at debugging. The nullptr is even returned if the field already exists but the initializer expression must be imported (this is the normal use case of this `Import` call?) and the import failed.
There are other places when nullptr is returned from `Import`, probably a warning should be made at every place (in all cases when the reason for returning nullptr is not another failed `Import` call).

Comment (martong) [reply lib/AST/ASTImporter.cpp:4608]: > There are other places when nullptr is returned from Import, probably a warning should be made at every place

Generally I agree. We should check the result of any import. But unfortunately there are multiple dozens of places where we don't do that. Just one example, in your latest PR #409, we do not check the result of the import of the methods (`Importer.Import(FromM);`).

I think we should target this and create a separate PR, where we do check the results of the `Import` call, in fact it should be LLVM_NODISCARD.

> The nullptr is even returned if the field already exists but the initializer expression must be imported 

I think, in this case we won't have a nullptr, since the field already exists.

File: lib/AST/ASTImporter.cpp [hunk 2]
```diff
@@ -2899,6 +2899,20 @@ Decl *ASTNodeImporter::VisitFieldDecl(FieldDecl *D) {
...
+        // initializer of a FieldDecl might not had been instantiated in the
+        // "To" context.  However, the "From" context might instantiated that,
+        // thus we have to merge that.
+        if (Expr *FromInitializer = D->getInClassInitializer()) {
+          // We don't have yet the initializer set.
+          if (FoundField->hasInClassInitializer() &&
+              !FoundField->getInClassInitializer()) {
+            Expr *ToInitializer = Importer.Import(FromInitializer);
+            if (!ToInitializer)
+              return nullptr;
```
Comment (balazske) [inline lib/AST/ASTImporter.cpp]: Probably it is not good to return `nullptr` here. `MapImported` was already called, so the new field is seen as imported. The `FoundField` can be returned, or ignore the errors, or call `MapImported` only if every import is successful and return `nullptr` if not.

Comment (martong) [reply lib/AST/ASTImporter.cpp]: Yeah, this is a good point :+1: 
I think, the only valid option then to return with the `FoundField`, even if we cannot import the Initializer.

The other options would not work, becasue if we call `MapImported` after `Import(FromInitializer)` then we end up having an infinite loop, because `VisitCXXDefaultInitExpr` starts with importing the `FieldDecl`.

**Review by balazske — APPROVED** [review]

**Comment by martong** [comment]
Squashed the commits into one.

**Comment by martong** [comment]
https://reviews.llvm.org/D50451
